# Mechanism / prior-art lines written for v1 rows that had "—". Key: legacy id → (mechanism or "", prior art or "").
# "none found" = no close ancestor found in this session's searches (weak evidence of novelty, not proof).
FILL = {
"L008": ("", "multimedia learning research (Mayer) argues for more than one"),
"L021": ("", "interdisciplinary curricula"),
"L023": ("", "mixed-methods research"),
"L032": ("", "micro-credentials"),
"L036": ("", "just-in-time learning"),
"L037": ("", "anti-gamification critiques"),
"L038": ("", "archival appraisal"),
"L051": ("", "one-sentence summaries"),
"L060": ("", "ambient learning apps"),
"L062": ("", "learning journals"),
"L064": ("", "clinical reasoning curricula"),
"L067": ("", "pruning in neural networks"),
"L068": ("", "homeostasis"),
"L071": ("", "symbiosis (biology)"),
"L073": ("", "metabolic rate as budget"),
"L075": ("", "mycorrhizal networks"),
"L078": ("", "learner models in ITS"),
"L080": ("", "automatic distractor generation research"),
"L081": ("", "fitness functions (evolutionary computing)"),
"L082": ("", "speciation (biology)"),
"L083": ("", "fossil records"),
"L084": ("", "crossover operators"),
"L085": ("", "niche construction theory (Odling-Smee)"),
"L088": ("sessions judged by learner-rated beauty so the attractive ones survive", "sexual selection (biology)"),
"L089": ("", "punctuated equilibrium (Eldredge & Gould)"),
"L090": ("", "horizontal gene transfer"),
"L092": ("", "setpoint control"),
"L094": ("", "control with dead time"),
"L096": ("", "gain scheduling (control engineering)"),
"L097": ("", "integrator anti-windup"),
"L098": ("", "feedforward control"),
"L099": ("", "adaptive setpoints"),
"L101": ("", "bang-bang control"),
"L103": ("", "controllability (Kalman)"),
"L104": ("", "limit-cycle detection"),
"L110": ("", "entropy of response distributions"),
"L111": ("", "triangulation"),
"L112": ("", "small-sample statistics"),
"L113": ("prefer the explanation with the shortest description that still predicts", "Kolmogorov complexity; minimum description length"),
"L114": ("", "mutual information"),
"L115": ("", "rate–distortion theory (Shannon)"),
"L117": ("show a bits-per-minute score for each session", "information rate"),
"L118": ("", "conservation practice"),
"L119": ("", "lossless compression"),
"L120": ("", "dictionary coding"),
"L122": ("", "executive summaries"),
"L123": ("", "summarisation assessment"),
"L125": ("", "over-simplification critiques"),
"L127": ("", "proof outlines"),
"L128": ("each mechanism gets exactly one canonical diagram reused everywhere", "visual vocabularies"),
"L130": ("", "curiosity-gap research (Loewenstein 1994)"),
"L131": ("", "CPU caches"),
"L132": ("", "prefetching"),
"L133": ("run two sessions' steps interleaved like a CPU pipeline", "instruction pipelining"),
"L134": ("", "branch prediction"),
"L136": ("", "hardware interrupts"),
"L137": ("", "memory-mapped IO"),
"L138": ("", "microcode"),
"L139": ("", "speculative execution"),
"L140": ("", "parallel processing"),
"L141": ("", "watchdog timers"),
"L142": ("", "low-power modes"),
"L143": ("a fixed battery of items run before and after each engine change", "benchmark suites (SPEC)"),
"L144": ("", "priority scheduling (OS)"),
"L145": ("", "process isolation (OS)"),
"L147": ("", "system calls"),
"L148": ("", "encapsulation"),
"L150": ("", "garbage collection"),
"L151": ("", "deadlock avoidance"),
"L153": ("", "package managers"),
"L154": ("", "hot code reload"),
"L155": ("", "crash recovery / journaling"),
"L156": ("several learners share one device with separate state", "multi-user operating systems"),
"L158": ("", "type checking"),
"L159": ("", "linkers"),
"L160": ("", "compiler optimisation"),
"L161": ("", "dead-code elimination"),
"L162": ("", "intermediate representations"),
"L163": ("", "static analysis"),
"L164": ("", "unit testing"),
"L165": ("", "JIT compilation"),
"L166": ("", "profile-guided optimisation"),
"L167": ("compile every session automatically into an audio version", "cross-compilation"),
"L168": ("sessions assembled from reusable text macros", "template engines"),
"L169": ("", "error messages that teach (Elm compiler)"),
"L170": ("", "eventual consistency"),
"L171": ("", "consensus protocols"),
"L172": ("", "Byzantine fault tolerance"),
"L173": ("", "idempotency"),
"L174": ("split the learner model into independent shards per domain", "database sharding"),
"L175": ("", "gossip protocols"),
"L176": ("", "leader election"),
"L177": ("", "quorum reads"),
"L178": ("scheduled check-in prompts asking how learning feels", "heartbeats"),
"L179": ("", "backpressure"),
"L180": ("", "local-first software (Kleppmann et al. 2019)"),
"L181": ("", "replication"),
"L182": ("the organ keeps working with no network and reconciles later", "CAP theorem / partition tolerance"),
"L184": ("", "inquiry tools"),
"L185": ("", "predict-observe-explain (White & Gunstone)"),
"L186": ("", "anomaly detection"),
"L187": ("", "replication crisis literature"),
"L189": ("", "measurement theory"),
"L190": ("", "controversy-based teaching"),
"L191": ("", "lab notebooks"),
"L193": ("reason by building and running a small model rather than recalling facts", "model-based reasoning (Nersessian)"),
"L194": ("the learner reviews a simulated paper and a simulated reviewer replies", "peer-review training"),
"L195": ("", "history-of-science cases"),
"L199": ("", "cue learning research"),
"L200": ("recordings of experts thinking aloud through cases", "think-aloud protocols (Ericsson & Simon)"),
"L201": ("", "fluency training (precision teaching)"),
"L202": ("", "error analysis"),
"L204": ("repeated confidence-rated items with feedback on calibration", "calibration training (Lichtenstein & Fischhoff)"),
"L205": ("a free-text journal of surprises", "prediction journals"),
"L206": ("", "variability of practice"),
"L207": ("a map of what experts fail to explain to novices", "expert blind spot (Nathan & Petrosino)"),
"L208": ("", "tacit knowledge elicitation"),
"L210": ("", "capstone problems"),
"L211": ("open models with no task, explored freely", "sandbox games"),
"L212": ("race through sessions against the clock", "speedrunning"),
"L213": ("puzzles where the right move is asking for the hidden variable", "hidden-information games"),
"L214": ("game levels unlocked by transfer scores", "level design"),
"L215": ("resume exactly where the learner stopped", "save systems"),
"L216": ("difficulty adapts silently from behaviour", "dynamic difficulty adjustment"),
"L217": ("an overarching story connects the seasons", "campaign design"),
"L218": ("badges for achievements", "gamification badges"),
"L219": ("", "cooperative games"),
"L220": ("", "New Game+ (games)"),
"L221": ("", "emergent gameplay"),
"L222": ("", "mystery narrative structure"),
"L223": ("", "history of ideas"),
"L224": ("the learner's own future self narrates why the idea matters", "possible selves research"),
"L225": ("sessions end on unresolved hooks to pull the learner back", "serial fiction"),
"L226": ("", "misconception-based teaching"),
"L227": ("stories of what would have happened otherwise, then checked against evidence", "counterfactual history"),
"L228": ("open with a story, extract the model, close with a new story using it", "case → principle → case teaching"),
"L230": ("", "character-driven narrative"),
"L231": ("stories whose branches follow the learner's predictions", "branching narratives"),
"L232": ("", "serial storytelling"),
"L233": ("each session opens with what goes wrong without the idea", "relevance interventions (Hulleman & Harackiewicz)"),
"L234": ("invented details added to real history for vividness", "historical fiction"),
"L235": ("", "comparative judgement"),
"L237": ("", "ablation in design critique"),
"L239": ("draw the thing to notice its structure", "drawing to learn"),
"L240": ("", "art as historical evidence"),
"L241": ("beauty ratings with confidence scored against panel agreement", "comparative judgement with calibration"),
"L242": ("reproduce a structure, then vary one element", "imitation exercises in craft education"),
"L243": ("a virtual walk through museum rooms", "virtual museum tours"),
"L244": ("design lessons from constraints (budget, material, site)", "design education"),
"L245": ("write a description of an artwork", "ekphrasis"),
"L246": ("grid and line overlays revealing composition", "composition analysis"),
"L247": ("", "open-access museum collections"),
"L249": ("", "reharmonisation exercises"),
"L250": ("teach rhythm as a feedback loop", "none found"),
"L251": ("", "musical form analysis"),
"L252": ("", "psychoacoustics"),
"L253": ("bundle public-domain recordings with provenance", "public-domain audio archives"),
"L254": ("follow a motif through a piece with fixed-option checkpoints", "motivic analysis"),
"L255": ("compare two performers of the same piece", "comparative listening"),
"L256": ("", "musical tension research"),
"L257": ("", "sociology of music"),
"L258": ("write down heard melodies", "ear-training dictation"),
"L259": ("teach silence as a structural element", "music theory"),
"L260": ("", "physics of consonance (Helmholtz)"),
"L261": ("read a building plan as an argument for how people should move", "architectural criticism"),
"L262": ("trace loads through a structure as a causal chain", "structural engineering"),
"L264": ("the same principle from a room to a city", "Powers of Ten (Eames)"),
"L266": ("walk through 3D models of buildings", "architectural walkthroughs"),
"L267": ("show how constraints produced a form", "form follows function"),
"L268": ("compare vernacular and monumental solutions to one problem", "vernacular architecture studies"),
"L269": ("teach design by examining the app's own structure", "dogfooding"),
"L270": ("", "induced demand (transport economics)"),
"L271": ("time-lapse of a city's growth", "urban history visualisations"),
"L272": ("building codes as a Goodhart case", "regulatory studies"),
"L273": ("teach light and material in architecture", "architectural design"),
"L274": ("show what the minutes are traded against", "opportunity cost"),
"L275": ("stop when the next minute is worth less than its alternative", "marginal analysis"),
"L276": ("audit what the app itself rewards", "mechanism design"),
"L277": ("representations bid for slots by past fitness", "markets"),
"L278": ("", "portfolio theory"),
"L279": ("", "sunk-cost research"),
"L280": ("teach what humans keep vs what machines do better", "comparative advantage"),
"L281": ("minutes treated as the budget currency", "time budgeting"),
"L282": ("count Renaissance's side effects on medicine", "externalities"),
"L284": ("AI help that removes effort also removes learning; no answer channel", "moral hazard"),
"L285": ("separate evidence of capability from signals of it", "signalling theory (Spence)"),
"L286": ("sessions auction for the daily slot", "auctions"),
"L288": ("never collapse evidence into one number", "Goodhart/Campbell's law"),
"L289": ("items never shown in sessions audit real learning", "held-out test sets"),
"L290": ("the learner may opt into a commitment contract", "commitment contracts (stickK)"),
"L291": ("", "incentive-compatible elicitation"),
"L292": ("occasionally verify self-reports against logs", "audits"),
"L293": ("no feature ever gives the learner the answer before commitment", "AI-tutor studies (Bastani et al. 2024)"),
"L294": ("hook results vote for the next season", "voting mechanisms"),
"L295": ("leaving never costs anything", "exit rights"),
"L296": ("tournaments with prizes", "competitions"),
"L297": ("difficulty reports scored against outcomes", "proper scoring"),
"L298": ("season bets written before release", "pre-registration"),
"L300": ("if-then plans in forges", "implementation intentions (Gollwitzer 1999)"),
"L302": ("messages praising effort", "growth-mindset interventions"),
"L304": ("retrieval as the main activity", "testing effect (Roediger & Karpicke 2006)"),
"L305": ("learner generates answers before reading them", "generation effect"),
"L306": ("no decorative details that distract", "seductive details research"),
"L307": ("check fluency with delayed items", "fluency illusions (Bjork)"),
"L308": ("raise arousal before sessions", "arousal and memory research"),
"L309": ("'others are learning now' nudges", "social proof"),
"L310": ("streaks that punish missed days", "loss aversion"),
"L311": ("scheduled nature breaks", "attention restoration theory"),
"L314": ("manage load per step", "cognitive load theory (Sweller)"),
"L315": ("reduce guidance as expertise grows", "expertise reversal effect (Kalyuga)"),
"L316": ("run the mechanism in the mind before seeing it", "mental simulation"),
"L317": ("group elements into chunks", "chunking (Miller; Chase & Simon)"),
"L318": ("tasks that use the body", "embodied cognition"),
"L319": ("interleave categories in practice", "interleaving (Rohrer)"),
"L320": ("build causal diagrams from cases", "causal model learning"),
"L321": ("learner predicts own recall; compared with outcome", "judgments of learning"),
"L322": ("transfer items ordered near to far", "analogical transfer research"),
"L323": ("introduce difficulties that aid long-term retention", "desirable difficulties (Bjork 1994)"),
"L326": ("open with a question that triggers curiosity", "curiosity and memory (Gruber et al. 2014)"),
"L327": ("committed predictions create prediction errors that aid memory", "prediction-error learning"),
"L328": ("sleep between study and test", "sleep and memory consolidation"),
"L329": ("", "reconsolidation research"),
"L330": ("design engagement around reward prediction", "reward-prediction dopamine research"),
"L331": ("train brain states with neurofeedback", "neurofeedback"),
"L332": ("exercise before sessions", "exercise and cognition"),
"L333": ("low-threat framing", "stress and learning research"),
"L334": ("", "pattern separation (hippocampus)"),
"L335": ("present in several senses at once", "multisensory learning"),
"L336": ("train general cognition with games", "brain training"),
"L337": ("schedule sessions at the best hour", "chronobiology"),
"L338": ("sessions in 20-minute blocks", "attention-span myth"),
"L339": ("experience a proof by manipulating the object", "proofs without words"),
"L340": ("find what stays constant", "invariance principles"),
"L341": ("check units to catch errors", "dimensional analysis"),
"L342": ("estimate powers of ten", "Fermi estimation"),
"L343": ("counts instead of percentages", "natural frequencies (Gigerenzer & Hoffrage 1995)"),
"L344": ("doubling and log scales as intuition", "exponential growth bias research"),
"L345": ("use symmetry to solve without calculation", "symmetry arguments"),
"L346": ("search for the counterexample", "Lakatos, Proofs and Refutations"),
"L347": ("proofs by picture", "proofs without words (Nelsen)"),
"L348": ("estimate probabilities by simulating", "Monte Carlo"),
"L349": ("primitives as a graph of dependencies", "concept graphs"),
"L350": ("formulas only when asked", "concreteness fading"),
"L351": ("therapy for maths anxiety", "maths-anxiety interventions"),
"L352": ("map arguments as premises and conclusions", "argument mapping (van Gelder)"),
"L353": ("find the unstated premise", "enthymeme analysis"),
"L354": ("state the strongest version of a view", "steelmanning"),
"L355": ("thought experiments as runnable models", "thought experiments"),
"L356": ("score humility by calibration", "intellectual humility research"),
"L357": ("track belief changes like code", "version control"),
"L358": ("dilemmas analysed with mechanisms", "case-based ethics"),
"L359": ("chatbot asks Socratic questions", "Socratic dialogue"),
"L360": ("philosophy of science through cases", "HPS teaching"),
"L361": ("paradoxes as click moments", "paradox pedagogy"),
"L362": ("definitions after the concept is built", "concept-first teaching"),
"L363": ("contested positions presented fairly", "teaching controversial issues"),
"L364": ("read whole treatises", "great books"),
"L365": ("cases from several cultures", "comparative studies"),
"L366": ("insider and outsider views", "emic/etic (Pike)"),
"L367": ("rituals as commitment devices", "anthropology of ritual"),
"L368": ("kinship networks as systems", "kinship studies"),
"L369": ("small observation tasks in daily life", "ethnographic fieldwork"),
"L370": ("Egyptian cases first where relevant", "culturally relevant pedagogy"),
"L371": ("audit where cases come from", "diversity audits"),
"L372": ("techniques from oral cultures", "oral tradition studies"),
"L373": ("gift economies as incentive systems", "Mauss, The Gift"),
"L374": ("taboos as information carriers", "anthropology of taboo"),
"L375": ("objects as evidence of culture", "material culture studies"),
"L376": ("institutions as solutions to problems", "institutional economics (North)"),
"L377": ("language determines thought", "Sapir–Whorf (strong form)"),
"L378": ("trace how a concept changed", "conceptual history (Koselleck)"),
"L379": ("what if one fact changed", "counterfactual reasoning"),
"L380": ("original archive numbers", "archival research"),
"L381": ("myths graded by evidence", "myth-busting"),
"L382": ("same event on different time scales", "Braudel's longue durée"),
"L383": ("parallel histories compared", "comparative history"),
"L384": ("roads not taken", "history of technology"),
"L385": ("historians' disputes presented", "historiography"),
"L386": ("timelines as causal models", "timeline visualisation"),
"L387": ("flag judgments using today's standards", "presentism critique"),
"L388": ("history as the deeds of great individuals", "great-man theory"),
"L389": ("", "prediction in history teaching"),
"L390": ("read whole histories", "narrative history"),
"L391": ("", "constitutional design"),
"L392": ("content audited by automated tests", "test-driven development"),
"L393": ("features expire unless renewed", "sunset clauses"),
"L394": ("the learner's time as a protected commons", "Ostrom's commons"),
"L395": ("", "separation of powers"),
"L396": ("", "appeals processes"),
"L397": ("", "transparency reports"),
"L398": ("audit every metric for gaming", "metric audits"),
"L399": ("rules for which sources may be used", "editorial standards"),
"L400": ("keep process to the minimum", "lean management"),
"L401": ("representations retire after a term", "term limits"),
"L402": ("seasons as federated units", "federalism"),
"L403": ("the kill switch written into the rules", "circuit breakers"),
"L404": ("primitives as shared infrastructure", "infrastructure studies"),
"L405": ("make seasons cheap to author", "authoring tools"),
"L406": ("", "redundancy engineering"),
"L407": ("one standard session format", "standards"),
"L408": ("split cognition between human and machine deliberately", "distributed cognition (Hutchins)"),
"L409": ("education as a public good", "public economics"),
"L410": ("archive of the learner's growth", "portfolios"),
"L411": ("facts tagged with a half-life", "Arbesman, The Half-Life of Facts"),
"L412": ("ideas evolve culturally", "cultural evolution (Boyd & Richerson)"),
"L413": ("institutions that produce truth", "social epistemology"),
"L414": ("energy budgets for the learner", "energy accounting"),
"L415": ("how ideas spread", "Rogers, Diffusion of Innovations"),
"L416": ("cases of collapse", "Diamond, Collapse"),
"L417": ("one primary button", "single-action UI"),
"L418": ("depth revealed on demand", "progressive disclosure"),
"L419": ("touch targets ≥ 44 px", "Apple HIG"),
"L420": ("", "friction logging"),
"L421": ("any answer can be undone", "undo systems"),
"L422": ("works offline first", "offline-first apps"),
"L423": ("no dark patterns", "dark-pattern research (Brignull)"),
"L424": ("voice interaction", "voice UIs"),
"L425": ("haptic feedback for confidence", "haptics"),
"L426": ("sheets over page navigation", "bottom sheets"),
"L427": ("no push notifications", "calm technology"),
"L428": ("accessible by default", "WCAG"),
"L429": ("sources on demand", "citations"),
"L430": ("AR overlays of loops in the world", "augmented reality"),
"L431": ("synthetic voice tutors", "TTS tutors"),
"L432": ("chat with simulated historical figures", "character bots"),
"L433": ("agents that negotiate time with the calendar", "scheduling agents"),
"L434": ("brain–computer interfaces", "BCI"),
"L435": ("models shared live with a friend", "collaborative simulations"),
"L436": ("sessions on live data", "data feeds"),
"L437": ("wearables trigger prompts", "wearables"),
"L438": ("3D models of mechanisms", "3D visualisation"),
"L439": ("animated films", "animation"),
"L440": ("models built in game engines", "game engines"),
"L442": ("generated images", "image generators"),
"L443": ("calibration curve shown on demand", "reliability diagrams"),
"L444": ("which observation would change this belief", "falsifiability"),
"L445": ("alerts when confidence and accuracy diverge", "calibration feedback"),
"L446": ("choose a strategy before solving", "strategy instruction"),
"L447": ("log what worked", "retrospectives"),
"L448": ("predict own score", "metacognitive monitoring"),
"L449": ("mistake types visible", "error taxonomies"),
"L450": ("probe the depth of explanations", "illusion of explanatory depth (Rozenblit & Keil)"),
"L451": ("tell when scaffolds are removed", "fading"),
"L452": ("self-assessment with rubrics", "rubrics"),
"L453": ("map of known unknowns", "knowledge mapping"),
"L454": ("estimate time before tasks", "planning fallacy"),
"L455": ("reflection prompts", "reflective practice"),
"L456": ("explain and predict together", "self-explanation"),
"L457": ("taste paired with mechanism", "design education"),
"L458": ("writing as reasoning", "writing to learn"),
"L459": ("speaking as compression", "elevator pitches"),
"L460": ("physical tasks with cognition", "embodied learning"),
"L461": ("social situations as incentive systems", "behavioural economics"),
"L462": ("medicine with base rates", "evidence-based medicine"),
"L463": ("founder work with Goodhart", "management by objectives critiques"),
"L464": ("acting to take perspectives", "drama in education"),
"L465": ("music training improves maths", "Mozart effect / far-transfer claims"),
"L466": ("predict what happened next in history", "forecasting in history teaching"),
"L467": ("art to train attention", "visual thinking strategies"),
"L468": ("negotiation with commitment", "Schelling, The Strategy of Conflict"),
"L469": ("open frontier questions per primitive", "review articles"),
"L470": ("random primitive draws", "random exploration"),
"L471": ("which field explains this phenomenon", "interdisciplinary problem framing"),
"L472": ("adjacent-possible map", "Kauffman's adjacent possible"),
"L473": ("pairs of distant cases", "serendipity engineering"),
"L474": ("find where experts disagree", "controversy mapping"),
"L475": ("an anomaly each week", "anomalies (Kuhn)"),
"L476": ("vault of questions", "question banks"),
"L477": ("detect avoided topics", "avoidance behaviour"),
"L478": ("random walks through an encyclopedia", "wiki rabbit holes"),
"L479": ("survey of blind spots", "self-report surveys"),
"L480": ("research digests", "newsletters"),
"L481": ("surprises across seasons", "spaced surprise"),
"L482": ("contract with the future self", "Ulysses contracts"),
"L483": ("learner's data as cases", "case-based reasoning"),
"L484": ("ledger of evidence", "evidence logs"),
"L485": ("registry of personal experiments", "pre-registration"),
"L486": ("the app audits itself inside lessons", "reflexive teaching"),
"L487": ("the dose shrinks itself", "adaptive dosing"),
"L488": ("the kill switch taught as sovereignty", "none found"),
"L489": ("minutes counted in receipts", "time tracking"),
"L490": ("stopping presented as the reward", "satisficing"),
"L491": ("medicine feeds the organ, never the reverse", "micro-frontends"),
"L492": ("myths graded inside lessons", "fact-checking"),
"L493": ("rejected ideas archived with reasons", "archives"),
"L494": ("one-tap reality check", "habit trackers"),
"L495": ("cluster wrong answers into bug classes", "misconception research"),
"L496": ("generate and test representations", "A/B testing"),
"L497": ("find verified cases for empty cells", "case libraries"),
"L498": ("evolve distractors from real errors", "distractor generation"),
"L499": ("reject sessions failing the schema", "linters"),
"L500": ("generate transfer items labelled by distance", "item generation"),
"L501": ("fit spacing per primitive", "spaced-repetition algorithms (FSRS)"),
"L502": ("templates for forges", "design templates"),
"L503": ("write the stakes line", "writing aids"),
"L504": ("check every claim has a source", "citation checkers"),
"L505": ("auto-build a season from a book", "summarisation tools"),
"L506": ("scripted learners test seasons", "simulated students"),
"L507": ("this registry", "idea registries"),
"L508": ("the learner assembles sessions for others", "learning by teaching"),
"L509": ("the learner builds the models", "constructionism (Papert)"),
"L510": ("habits run without the app", "fading"),
"L511": ("real events replace authored lessons", "experiential learning (Kolb)"),
"L512": ("join people who practise the idea", "Lave & Wenger"),
"L513": ("take part in real research", "citizen science"),
"L514": ("making things as the curriculum", "maker education"),
"L515": ("human mentors", "mentoring"),
"L516": ("life organised around good questions", "inquiry-based learning"),
"L517": ("tools that extend thought", "Engelbart's augmentation"),
"L518": ("reality as the teacher", "cognitive apprenticeship (Collins et al.)"),
"L519": ("the learner designs seasons", "self-directed learning"),
"L520": ("the organ stops", "graduation"),
}
