#!/usr/bin/env node
// Knowledge half-life and re-verification (§100, §133; M1 §105–106 knowledge recompiler).
//
// Every claim the seasons make carries a source and a year (provenance). Facts decay at different speeds: a primary
// text does not change; a finding in a fast field (medicine, technology, statistics about the present) can be
// overturned in a few years. This tool gives each claim a half-life class and a re-verification date, lists what is
// due, and writes docs/RENAISSANCE/completion/REVERIFY.json and .md. It does not browse: re-verification is a person's
// (or a supervised session's) job, done with current sources, then recorded by moving LAST_CHECKED.
//
// Usage: node tools/renaissance/halflife.js [--write] [--at 2026-09-26]
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const ROOT = path.resolve(__dirname, '..', '..');
// when the claims were last checked: every provenance entry was written and checked while its season was built
const LAST_CHECKED = { s1: '2026-09-24', s2: '2026-09-25', s3: '2026-09-26' };
// years before a claim must be looked at again
const HALF = { stable: null, slow: 10, medium: 5, fast: 2 };
const FAST = /\b(today|now|current|currently|recent|latest|guidelines?)\b/i;
const MEDIUM = /\b(medicine|clinical|patients?|doctors?|hospital|epidemic|cholera|statistic|study|studies|experiment|bevan|evidence)\b/i;

function claims() {
  const w = { window: {} };
  const ctx = vm.createContext(w);
  for (const f of ['s1', 's2', 's3a', 's3b', 's3c']) vm.runInContext(fs.readFileSync(path.join(ROOT, 'source/public/renaissance-' + f + '.js'), 'utf8'), ctx);
  const out = [];
  for (const z of w.window.RENAISSANCE_SEASONS || [])
    for (const s of z.sessions || [])
      for (const p of s.provenance || []) out.push({ season: z.id, session: s.id, id: p.id, kind: p.kind || '', year: p.year || '', source: p.source || '', claim: p.claim || '', license: p.license || '', contested: p.contested || null });
  return out;
}
function classify(c) {
  if (/^q\./.test(c.id) || c.kind === 'primary') return 'stable'; // a text or a primary source does not change; its wording was checked
  if (c.kind === 'original') return 'stable'; // the project's own teaching numbers, labelled as such
  const text = c.claim + ' ' + c.source;
  if (FAST.test(text)) return 'fast';
  if (MEDIUM.test(text) || c.contested) return 'medium';
  return 'slow';
}
const addYears = (d, y) => { const t = new Date(d + 'T00:00:00Z'); t.setUTCFullYear(t.getUTCFullYear() + y); return t.toISOString().slice(0, 10); };
function run(at) {
  const today = at || new Date().toISOString().slice(0, 10);
  const rows = claims().map((c) => {
    const cls = classify(c), last = LAST_CHECKED[c.season] || '2026-09-26';
    return Object.assign(c, { class: cls, lastChecked: last, reverifyBy: HALF[cls] ? addYears(last, HALF[cls]) : null });
  });
  const due = rows.filter((r) => r.reverifyBy && r.reverifyBy <= today);
  const counts = rows.reduce((a, r) => ((a[r.class] = (a[r.class] || 0) + 1), a), {});
  const noYear = rows.filter((r) => !r.year).map((r) => r.session + ':' + r.id);
  return { at: today, total: rows.length, counts, due: due.map((r) => r.session + ':' + r.id), noYear, next: rows.filter((r) => r.reverifyBy).sort((a, b) => (a.reverifyBy < b.reverifyBy ? -1 : 1)).slice(0, 12).map((r) => ({ id: r.session + ':' + r.id, by: r.reverifyBy, class: r.class })), rows };
}
function md(r) {
  let s = '# Re-verification schedule (knowledge half-life)\n\nGenerated by `tools/renaissance/halflife.js` on ' + r.at + ' from every provenance entry in the seasons (' + r.total + ' claims). Stable: primary texts, registered quotations and the project\'s own labelled numbers. Fast (2 years): claims about the present, guidelines, trials, markets and technology. Medium (5 years): medicine, statistics and contested findings. Slow (10 years): settled history and science.\n\n';
  s += '| class | claims |\n|---|---|\n' + Object.entries(r.counts).map(([k, v]) => '| ' + k + ' | ' + v + ' |').join('\n') + '\n\n';
  s += '**Due now:** ' + (r.due.length ? r.due.join(', ') : 'none') + '.\n\n**Next to re-check:**\n\n' + r.next.map((x) => '- `' + x.id + '` by ' + x.by + ' (' + x.class + ')').join('\n') + '\n\nClaims without a year: ' + (r.noYear.length ? r.noYear.join(', ') : 'none') + '.\n';
  return s;
}
if (require.main === module) {
  const a = process.argv.slice(2);
  const r = run(a.includes('--at') ? a[a.indexOf('--at') + 1] : null);
  if (a.includes('--write')) {
    const dir = path.join(ROOT, 'docs/RENAISSANCE/completion');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'REVERIFY.json'), JSON.stringify({ at: r.at, total: r.total, counts: r.counts, due: r.due, noYear: r.noYear, claims: r.rows.map((x) => ({ id: x.session + ':' + x.id, class: x.class, year: x.year, lastChecked: x.lastChecked, reverifyBy: x.reverifyBy })) }, null, 1) + '\n');
    fs.writeFileSync(path.join(dir, 'REVERIFY.md'), md(r));
  }
  console.log(r.total + ' claims · ' + JSON.stringify(r.counts) + ' · due now ' + r.due.length + ' · without a year ' + r.noYear.length);
}
module.exports = { run, classify, claims, md };
