// RENAISSANCE requirement graph, source of truth (§4). Every numbered section of the three missions maps to one or
// more canonical requirement nodes (requirement_map.js); the coverage oracle (oracle.js) checks every claim a node makes
// against the repository and the latest test results, and writes REQUIREMENT_GRAPH.json and the COMPLETION_LEDGER.
//
// Kinds decide what "closed" means:
//   build · guard   code + tests that exist and passed; status UNIT-TESTED or higher
//   doc             the document exists (and names what it must); status IMPLEMENTED or higher
//   process         how the work is done; evidence plus a document or a test; status IMPLEMENTED or higher
//   principle       a rule with an operationalisation (the guard or document that enforces it)
//   rollup          closed exactly when every dependency is closed
//   empirical       needs real time and real performance; never closed by code; queued with a due date
//   frontier        open by design (§169, §235: no terminal syllabus); machinery closed elsewhere, volume queued
// External blockers must name the blocker and the preparatory work already done (§186, §277).
'use strict';
const R = (...ids) => ids.map((i) => 'rn:' + i);
const V3 = (...ids) => ids.map((i) => 'v3:' + i);
const OM = (...ids) => ids.map((i) => 'om:' + i);
const CO = (...ids) => ids.map((i) => 'co:' + i);
const ENG = 'source/public/renaissance-v1.js';
const S1 = 'source/public/renaissance-s1.js', S2 = 'source/public/renaissance-s2.js', S3A = 'source/public/renaissance-s3a.js', S3B = 'source/public/renaissance-s3b.js', S3C = 'source/public/renaissance-s3c.js';
const D = 'docs/RENAISSANCE/', O = 'docs/RENAISSANCE/omega/', C3 = 'docs/RENAISSANCE/v3/', CP = 'docs/RENAISSANCE/completion/';
const nodes = [];
const N = (id, cat, kind, name, o) => nodes.push(Object.assign({ id, cat, kind, name, why: '', deps: [], status: 'DISCOVERED', docs: [], code: [], tests: [], bench: [], effect: '', blocker: null, evidence: '', sup: null, reason: null, due: null }, o));

/* ── the experience ── */
N('door', 'experience', 'build', 'One door after the day\'s medicine; the life-first gate', { why: 'The organ must never compete with medicine or sleep (§114, M1 §113).', status: 'INTEGRATION-TESTED', code: [ENG + '#function gate('], tests: R('R1', 'R2', 'R16', 'R17', 'R19'), docs: [D + '03_ARCHITECTURE.md'], effect: 'After STOP MEDICINE one door appears with today\'s question and CONTINUE.', evidence: 'Gate shut until medicine is done, shut 01:00–05:00 and on exam weekend, shrinks after 245 min a week.' });
N('controls', 'experience', 'build', 'The surface controls (§156): CONTINUE, SHOW ME DIFFERENTLY, THIS DIDN\'T CLICK, I ALREADY GET THIS, GO DEEPER, WHY THIS?, SHOW SOURCE, DONE', { status: 'INTEGRATION-TESTED', code: [ENG + '#["deeper", "GO DEEPER"]', ENG + '#function sourceSheet('], tests: R('R3', 'R4', 'R5', 'R8', 'R9', 'R7').concat(V3('V5')), docs: [O + '06_DAY_AND_DECADE.md'], effect: 'Eight buttons; nothing else to learn.', evidence: 'Each control tested for its effect, not its presence.' });
N('ease', 'experience', 'principle', 'Objective depth, subjective ease; the final paradox (simple surface, deep machine)', { why: '§81, M1 §8, M1 §200, M2 §2.', status: 'IMPLEMENTED', tests: R('R3', 'R4', 'R5', 'R34'), docs: [D + '03_ARCHITECTURE.md'], evidence: 'Hardness is attacked by bridges on demand, a second representation and the dose, not by removing depth.' });
N('inside', 'experience', 'guard', 'Everything inside the experience: no links out, no open-ended tasks, isolated from the CNS organ (not a copy of it)', { status: 'INTEGRATION-TESTED', code: [ENG + '#const KEY = "renaissance_v1"'], tests: R('R12', 'R22'), docs: [D + '07_SEASON_1.md'], effect: 'Nothing sends him elsewhere to find the content.', evidence: 'Lint for links out and open-ended prompts; a whole session changes no CNS storage.' });
N('stoprule', 'experience', 'build', 'The stop rule: one session a day, DONE at any moment, nothing owed', { status: 'INTEGRATION-TESTED', code: [ENG + '#const doneToday'], tests: R('R9', 'R11', 'R15'), docs: [D + '03_ARCHITECTURE.md'], effect: 'The door says the day is done.' });
N('nodebt', 'experience', 'build', 'No backlog debt, no reading guilt, no FOMO: a missed day recompiles, it is never owed', { status: 'INTEGRATION-TESTED', code: [ENG + '#function plan('], tests: R('R18', 'R27'), docs: [D + '03_ARCHITECTURE.md'], effect: 'After twelve missed days the door offers one ordinary session.' });
N('dose', 'experience', 'build', 'Minimum effective dose; session length optimised, not fixed (short, full, deep)', { status: 'INTEGRATION-TESTED', code: [ENG + '#const DOSE'], tests: R('R16', 'R27').concat(V3('C3')), docs: [D + '03_ARCHITECTURE.md'] });
N('deep', 'experience', 'build', 'Deep weekend experiences (cognitive overclock, §119) gated by the week\'s budget', { status: 'INTEGRATION-TESTED', code: [ENG + '#DOSE.deep'], tests: V3('C3'), docs: [C3 + '03_ENGINE.md'] });
N('why', 'experience', 'build', 'WHY THIS?: every choice is auditable (M1 §183)', { status: 'INTEGRATION-TESTED', code: [ENG + '#function whySheet('], tests: R('R7').concat(V3('C1', 'D3')), effect: 'The compiler\'s reasons, the trials and the record are one tap away.' });
N('receipt', 'experience', 'build', 'Intellectual receipts (§165): capability, cultural and model delta, errors, transfer, next retrieval, uncertainty', { status: 'INTEGRATION-TESTED', code: [ENG + '#**Possession:**'], tests: R('R10').concat(V3('V6')), docs: [O + '06_DAY_AND_DECADE.md'] });
N('nodash', 'experience', 'guard', 'No dashboard hell, no gamification slop, no machine bureaucracy (§157, M1 §125, M1 §187)', { status: 'INTEGRATION-TESTED', tests: R('R22', 'R3'), code: [ENG + '#function whySheet('], docs: [D + '02_FAILURE_UNIVERSE.md'], evidence: 'No XP, streaks or leaderboards in any Renaissance text; progress lives behind WHY THIS?.' });
N('a11y', 'experience', 'guard', 'Accessibility (§158): phone, tablet, desktop, touch, keyboard, contrast, no microtext, no cropping or overlap', { status: 'INTEGRATION-TESTED', code: ['source/public/renaissance-v1.css#min-height:44px'], tests: R('R24', 'R34').concat(V3('A1', 'V4')) });
N('perf', 'experience', 'guard', 'Performance (§159): a session opens fast and every model redraws fast', { status: 'INTEGRATION-TESTED', code: [ENG + '#function open('], tests: V3('A2') });
N('device', 'experience', 'build', 'Device independence and the future-interface path: one-file export and import, voice-ready speech of every step', { status: 'INTEGRATION-TESTED', code: [ENG + '#function importState(', ENG + '#speakable'], tests: V3('D1', 'D2') });
N('recovery', 'experience', 'build', 'Failure recovery (§247): corruption detection, safe default, rollback, kill switches', { status: 'INTEGRATION-TESTED', code: [ENG + '#renaissance_v1_corrupt_'], tests: V3('D3', 'E3').concat(R('R19')) });
N('attention', 'experience', 'principle', 'Human attention and density (§174–176): modality shifts inside a session; rich, not packed; no content firehose', { status: 'IMPLEMENTED', tests: R('R21'), docs: [D + '07_SEASON_1.md'], evidence: 'Every session alternates prediction, story, visual, primary text, model, comparison and creation, and fits ≤ 30 minutes (deep ≤ 45).' });
N('privacy', 'experience', 'build', 'Learner data per project policy (§195): the record lives on the device, exports only on request, sealed answers keep ids not words', { status: 'INTEGRATION-TESTED', code: [ENG + '#schema: "renaissance.state/1"'], tests: R('R12').concat(V3('P2', 'D1')) });
N('sovereignty', 'experience', 'build', 'Sovereignty (§197, §297): the learner is the final authority; every adaptive part has an off switch', { status: 'INTEGRATION-TESTED', code: [ENG + '#renaissance_experiments', ENG + '#renaissance_probes'], tests: R('R19').concat(V3('E3')), evidence: 'Kill switches for the organ, the trials and the sealed probes.' });
N('life', 'experience', 'build', 'Intellectual life must not replace life (§114, §213, §290): sleep, exam and weekly caps', { status: 'INTEGRATION-TESTED', code: [ENG + '#WEEK_STOP'], tests: R('R1', 'R16', 'R17') });
N('noaddiction', 'experience', 'guard', 'No manipulative engagement (§196, M2 §137): no streaks, no variable rewards, a stop rule', { status: 'INTEGRATION-TESTED', tests: R('R22', 'R11'), code: [ENG + '#const doneToday'] });

/* ── truth, sources, rights ── */
N('provenance', 'truth', 'build', 'Provenance per claim with graded sources and the source hierarchy (§135, M1 §107, M1 §139)', { status: 'INTEGRATION-TESTED', code: [ENG + '#const prov = '], tests: R('R20', 'R7').concat(V3('V1')), docs: [D + '01_RESEARCH.md'] });
N('quotes', 'truth', 'build', 'Quote engine (§13): exact wording, translator, edition, speaker, scene, context, meaning, why it matters, misattribution risk, rights, how it was checked', { status: 'INTEGRATION-TESTED', code: [S3A + '#const quotes = {', ENG + '#function sourceSheet('], tests: V3('V1', 'V5', 'M1'), docs: [C3 + '01_POSSESSION.md'] });
N('nohalluc', 'truth', 'guard', 'No hallucinated culture (§136, M1 §108): no invented quotes, scenes, plot events or results; hedges where the record is thin', { status: 'INTEGRATION-TESTED', tests: R('R20').concat(V3('V1', 'M1')), docs: [D + '07_SEASON_1.md', D + '08_SEASON_2.md', C3 + '02_ORGANS.md'], evidence: 'Every quotation registered with how it was checked; plot claims carry provenance; season audits list what was corrected.' });
N('conflict', 'truth', 'guard', 'Source conflict (§137): disagreement preserved, contested claims shown as contested', { status: 'IMPLEMENTED', code: [ENG + '#**Contested:**'], docs: [C3 + '01_POSSESSION.md'] });
N('rights', 'truth', 'build', 'Rights architecture (§134, M1 §140): eight source classes, every object classed', { status: 'INTEGRATION-TESTED', code: ['source/public/renaissance-media.js#rights: ['], tests: V3('M1').concat(R('R20')), docs: [C3 + '05_RIGHTS_MEDIA_FUTURE.md'] });
N('media', 'truth', 'build', 'Rights-aware media registry (§138, M1 §143): every visual, model, listening passage, quotation and data object with type, rights, source and job', { status: 'INTEGRATION-TESTED', code: ['source/public/renaissance-media.js#window.RENAISSANCE_MEDIA', ENG + '#function media('], tests: V3('M1'), docs: [C3 + '05_RIGHTS_MEDIA_FUTURE.md'] });
N('noslopvis', 'truth', 'guard', 'No AI-slop visuals (§139): every visual states the thinking it does and is used by a step', { status: 'INTEGRATION-TESTED', tests: V3('M1', 'Q1'), code: ['source/public/renaissance-media.js#job'] });
N('oatmeal', 'truth', 'guard', 'No AI oatmeal and the no-slop reviewer (§15, §220)', { status: 'INTEGRATION-TESTED', tests: V3('Q1').concat(R('R22')), code: [ENG + '#function qView('] });
N('antipretension', 'truth', 'guard', 'Anti-bullshit and anti-pretension (§94, §150, M1 §159): jargon, authority theatre and pretension are diagnosed errors', { status: 'ADVERSARIALLY-TESTED', tests: R('R35').concat(V3('S3', 'Q1')), code: [ENG + '#pretension:'] });
N('texture', 'truth', 'guard', 'Texture, not trivia (§227–229, M1 §209): enough detail to converse, no quote dumping, quotations emerge in context', { status: 'IMPLEMENTED', docs: [C3 + '01_POSSESSION.md'] });
N('claims', 'truth', 'guard', 'No fake precision, no IQ or guarantee claims, no founder flattery (§38, §166, §285, M1 §136, M1 §223, M2 §144)', { status: 'INTEGRATION-TESTED', tests: V3('L1', 'G2', 'F1'), code: [ENG + '#e.n >= 5'], docs: [D + '05_BENCHMARKS.md'] });

/* ── content, organs and possession ── */
N('boot', 'content', 'build', 'Cognitive bootloader (§35): the 21 primitives of seasons 1–2, run first and in order', { status: 'INTEGRATION-TESTED', code: [S1 + '#boot: true', S2 + '#boot: true'], tests: R('R21', 'R28').concat(V3('V3', 'C1')), docs: [D + '07_SEASON_1.md', D + '08_SEASON_2.md'] });
N('arc', 'content', 'build', 'Session arc (M1 §148, M2 §168): predictions, a model, two cases, near and far transfer, a forge, hooks; the understanding compiler', { status: 'INTEGRATION-TESTED', tests: R('R21'), code: [ENG + '#function plan('] });
N('precise', 'content', 'guard', 'Precise cognitive tasks (§77–78): one right option, every wrong option a named misconception with its repair (precomputed branching)', { status: 'INTEGRATION-TESTED', tests: R('R20', 'R6', 'R22'), code: [ENG + '#const BUGS'] });
N('vocab', 'content', 'build', 'Vocabulary firewall (§79–80): plain idea, hook, term, definition, limit; Egyptian-Arabic micro-hooks', { status: 'INTEGRATION-TESTED', tests: R('R20', 'R32'), code: [ENG + '#function vocabSheet(', S3A + '#vocab:'] });
N('reps', 'content', 'build', 'Representation singularity (§69): competing representations per idea; scale and model zoom by switching representation', { status: 'INTEGRATION-TESTED', tests: R('R4', 'R32'), code: [ENG + '#data-kind='] });
N('satisfaction', 'content', 'build', 'Intellectual satisfaction (§83): confusion → revelation → power, inside every session', { status: 'INTEGRATION-TESTED', tests: R('R21', 'R6'), code: [ENG + '#stage'] });
N('curiosity', 'content', 'build', 'Curiosity engine (§82): legitimate information gaps (the door\'s question), no clickbait', { status: 'INTEGRATION-TESTED', tests: R('R2', 'R21'), code: [ENG + '#hook'] });
N('click', 'content', 'build', 'Click events (§84, M2 §16): moments when facts collapse into one model are logged', { status: 'IMPLEMENTED', code: [ENG + '#clicks'] });
N('boredom', 'content', 'build', 'Boredom and friction engine (§85, M1 §154): THIS DIDN\'T CLICK names the cause, I ALREADY GET THIS skips ahead', { status: 'INTEGRATION-TESTED', tests: R('R5', 'R8'), code: [ENG + '#XRAY_OF'] });
N('xray', 'content', 'build', 'Cognitive X-ray (§76): a wrong answer names the missing mechanism; failure is curriculum data', { status: 'INTEGRATION-TESTED', tests: R('R5', 'R20'), code: [ENG + '#XRAY_OF'] });
N('prereq', 'content', 'build', 'Prerequisite annihilator and difficulty arbitrage (§68): bridges on demand, notational tax removed, real dependencies kept (requires)', { status: 'INTEGRATION-TESTED', tests: R('R5').concat(V3('V1')), code: [ENG + '#bridge'] });
N('wormholes', 'content', 'build', 'Cross-domain wormholes, zip bombs, anti-specialisation, the polymath compiler (§64–67): every session\'s far-transfer item reuses real structure elsewhere', { status: 'INTEGRATION-TESTED', tests: R('R21').concat(V3('L3')), code: [ENG + '#function multiplex('] });
N('threebox', 'content', 'build', 'Three-box compression with an overcompression test (§40, M2 §9, M2 §134)', { status: 'INTEGRATION-TESTED', tests: R('R23', 'R31'), code: [S2 + '#mechs'] });
N('intuition', 'content', 'build', 'Intuition synthesiser (§88): contrasts, anomalies and edge cases in every session', { status: 'INTEGRATION-TESTED', tests: R('R21'), code: [ENG + '#function contrastView('] });
N('discovery', 'content', 'build', 'Historical possession, discovery reenactment, counterfactual civilisation, lost futures (§89–92): Semmelweis, Snow, van Helmont, Euler, Hooke, the medicine relay', { status: 'INTEGRATION-TESTED', tests: R('R21').concat(V3('V6')), code: [S3B + '#van Helmont', S1 + '#Semmelweis'] });
N('taste', 'content', 'build', 'Taste, beauty and perceptual resolution (M1 §60–61, M2 §55–57, §200): blind comparisons before names', { status: 'INTEGRATION-TESTED', tests: R('R29', 'R30'), code: [S2 + '#chartBad'] });
N('question', 'content', 'build', 'Decisive-question engine and question singularity (§41, §55): the question whose answer changes the decision', { status: 'INTEGRATION-TESTED', tests: R('R23', 'R21'), code: [S2 + '#voi'] });
N('explain', 'content', 'build', 'Explanation supremacy and the beautiful-explanation trap (§148): every explanation is followed by unseen transfer', { status: 'INTEGRATION-TESTED', tests: R('R21').concat(V3('P4')), code: [ENG + '#kind'] });
N('creation', 'content', 'build', 'Creation engine: the forge in every session (M1 §71)', { status: 'INTEGRATION-TESTED', tests: R('R10', 'R21').concat(V3('F1')), code: [ENG + '#function forgeView('] });
N('invention', 'content', 'build', 'Invention engine and recombination (§54): constraints, mechanisms, candidates, a falsifying critique', { status: 'INTEGRATION-TESTED', tests: R('R21').concat(V3('V6')), code: [S3B + '#hankin', S3C + '#chain'] });
N('realitybridge', 'content', 'build', 'Reality bridge and life-as-lab (§106–107, M1 §74–77): the next day asks whether the built device met reality; screens send him out when reality teaches better', { status: 'INTEGRATION-TESTED', code: [ENG + '#function realityView('], tests: R('R14').concat(V3('F1')), docs: [D + '03_ARCHITECTURE.md'] });
N('boss', 'content', 'build', 'Boss worlds and synthesis trials (§122, M1 §66–67, M1 §70): unlabelled, integrated, weekly', { status: 'INTEGRATION-TESTED', tests: R('R31').concat(V3('C3')), code: [S2 + '#boss'] });
N('foundry', 'content', 'build', 'Experience foundry and new media (§86–87): forge, reality tap, blind pair, unlabelled world, sealed probes, synthesised listening, reading-speed passages', { status: 'INTEGRATION-TESTED', tests: R('R29', 'R31').concat(V3('V5', 'P1')), docs: [D + '04_INVENTION_REGISTRY.md'] });
N('newsense', 'content', 'build', 'New-sense generator (M1 §24, M2 §22): trained perceptions such as seeing doubling on a log scale', { status: 'INTEGRATION-TESTED', tests: R('R23'), code: [S2 + '#growth'], docs: [O + '05_GENOME_AND_ENGINES.md'] });
N('masterpiece', 'possession', 'build', 'Masterpiece compiler (§9–10): non-uniform compression; read whole, read passages, bridge, or do not read', { status: 'INTEGRATION-TESTED', code: [S3A + '#compileMap'], tests: V3('V1', 'V6', 'L4'), docs: [D + '10_MASTERPIECE_COMPILER.md'] });
N('karamazov', 'possession', 'build', 'The Brothers Karamazov prototype (§11, §268): three sessions, passages, family map, argument model, trial, criticism, discussion', { status: 'INTEGRATION-TESTED', code: [S3A + '#id: "km1"', S3A + '#id: "km3"'], tests: V3('V6', 'V1', 'P5'), docs: [D + '10_MASTERPIECE_COMPILER.md'] });
N('mq', 'possession', 'guard', 'Masterpiece experience quality (§217): primary material, map, character graph, vocabulary, context, criticism, quotations, transfer, discussion, memory, reader-Turing evaluation', { status: 'IMPLEMENTED', docs: [D + '10_MASTERPIECE_COMPILER.md'] });
N('possession', 'possession', 'build', 'Cultural possession ladder and graph (§8, §162): twelve rungs earned by evidence', { status: 'INTEGRATION-TESTED', code: [ENG + '#const LADDER'], tests: V3('L4', 'V6'), docs: [C3 + '01_POSSESSION.md'] });
N('readerturing', 'possession', 'build', 'Reader Turing test (§12, §146): sealed questions unseen by the lesson author, 30 days after the last session', { status: 'ADVERSARIALLY-TESTED', code: [ENG + '#rt-'], tests: V3('P5', 'S1', 'S2'), docs: ['docs/RENAISSANCE/sealed/README.md'] });
N('primary', 'possession', 'build', 'Primary-experience engine (§14, M1 §5, M2 §5): passages whole, synthesised listening, live models; summary where it loses nothing', { status: 'INTEGRATION-TESTED', code: [ENG + '#function passageView(', ENG + '#const AUDIO'], tests: V3('V5', 'V7', 'L4') });
N('civgraph', 'possession', 'build', 'Civilisation graph and compression (§236–237, M1 §27): works, people, ideas, places and influence', { status: 'INTEGRATION-TESTED', code: ['source/public/renaissance-civ.js#window.RENAISSANCE_CIV'], tests: V3('V2') });
N('lit', 'organ', 'build', 'Literature organ (§16): a novel (Karamazov) and a poem (Ozymandias), each read, mapped and argued', { status: 'INTEGRATION-TESTED', code: [S3A + '#id: "ozy"'], tests: V3('V1', 'V6'), docs: [C3 + '02_ORGANS.md'] });
N('math', 'organ', 'build', 'Mathematics organ (§17): Euler\'s bridges as intuition, representation, proof and beauty', { status: 'INTEGRATION-TESTED', code: [S3B + '#id: "euler"'], tests: V3('V1', 'V6'), docs: [C3 + '02_ORGANS.md'] });
N('science', 'organ', 'build', 'Science organ (§18): world-model building (van Helmont\'s willow, where fat goes) plus seasons 1–2 mechanisms', { status: 'INTEGRATION-TESTED', code: [S3B + '#id: "willow"'], tests: V3('V1', 'V6'), docs: [C3 + '02_ORGANS.md'] });
N('history', 'organ', 'build', 'History organ (§19): one line of medicine from Galen to Europe through Arabic; chronology, institutions, transmission', { status: 'INTEGRATION-TESTED', code: [S3C + '#id: "wisdom"'], tests: V3('V1', 'V6'), docs: [C3 + '02_ORGANS.md'] });
N('philosophy', 'organ', 'build', 'Philosophy organ (§20): problems, not doxography (the Inquisitor\'s argument, premises switched off)', { status: 'INTEGRATION-TESTED', code: [S3A + '#id: "km2"'], tests: V3('V1', 'V6'), docs: [C3 + '02_ORGANS.md'] });
N('art', 'organ', 'build', 'Art organ (§21): seeing the rule behind a pattern (Hankin\'s method), blind comparisons', { status: 'INTEGRATION-TESTED', code: [S3B + '#id: "pattern"'], tests: V3('V1', 'V6').concat(R('R29')), docs: [C3 + '02_ORGANS.md'] });
N('music', 'organ', 'build', 'Music organ (§22): hearing cadence, question and answer, and a maqam interval, from exact pitches', { status: 'INTEGRATION-TESTED', code: [S3B + '#id: "cadence"'], tests: V3('V1', 'V6', 'V7'), docs: [C3 + '02_ORGANS.md'] });
N('film', 'organ', 'build', 'Film organ (§23): the 180-degree line, camera placement and screen direction', { status: 'INTEGRATION-TESTED', code: [S3C + '#id: "cut"'], tests: V3('V1', 'V6'), docs: [C3 + '02_ORGANS.md'] });
N('architecture', 'organ', 'build', 'Architecture organ (§24): structure you can feel (the hanging chain and the arch)', { status: 'INTEGRATION-TESTED', code: [S3C + '#id: "arch"'], tests: V3('V1', 'V6'), docs: [C3 + '02_ORGANS.md'] });
N('religion', 'organ', 'build', 'Religion and civilisation organ (§25): theological distinctions with textual seriousness (the Inquisitor, Zosima, theodicy), no mockery and no preaching', { status: 'INTEGRATION-TESTED', code: [S3A + '#theodicy'], tests: V3('V6'), docs: [C3 + '02_ORGANS.md'] });
N('global', 'organ', 'guard', 'Global civilisation coverage (§26, M2 §141): ten regions as settings of real content, not Europe plus tokens', { status: 'INTEGRATION-TESTED', tests: V3('V3'), code: [S3A + '#region:'] });
N('arabic', 'organ', 'build', 'Arabic and Islamic intellectual civilisation (§27): Hunayn and Avicenna, girih patterns, maqam, paper in Baghdad', { status: 'INTEGRATION-TESTED', tests: V3('V3', 'V7'), code: [S3C + '#Hunayn'], docs: [C3 + '02_ORGANS.md'] });
N('cultivation', 'organ', 'build', 'High-cultivation organ without pretension or class performance (§28, §230–231)', { status: 'INTEGRATION-TESTED', code: [S3C + '#id: "salon"'], tests: V3('V6', 'Q1'), docs: [C3 + '02_ORGANS.md'] });
N('society', 'organ', 'build', 'High-society navigation (§29): introductions, hosting, formal dining, dress, range, graceful disagreement, listening, calibration', { status: 'PROTOTYPED', code: [S3C + '#register'], docs: [C3 + '02_ORGANS.md'], evidence: 'The salon session trains range, register and graceful disagreement; hosting, dining and dress are not built.' });
N('salon', 'organ', 'build', 'Salon test (§30): a conversation that moves unpredictably across fields', { status: 'INTEGRATION-TESTED', code: [S3C + '#id: "salon"'], tests: V3('V6'), docs: [C3 + '02_ORGANS.md'] });
N('museum', 'organ', 'build', 'Museum test (§31): does he see more than before (perceptual resolution, not labels)', { status: 'PROTOTYPED', code: [S3B + '#id: "pattern"'], docs: [C3 + '02_ORGANS.md'] });
N('concert', 'organ', 'build', 'Concert test (§32): does he hear structure, difference, tension, resolution, style', { status: 'PROTOTYPED', code: [S3B + '#id: "cadence"'], docs: [C3 + '02_ORGANS.md'] });
N('conversation', 'organ', 'build', 'Conversation test and conversation transfer (§33, §226, M1 §160): no trivia flexing, fake certainty, quote dumping or pretension', { status: 'INTEGRATION-TESTED', code: [S3A + '#id: "t13"'], tests: V3('V6', 'S3'), docs: [C3 + '02_ORGANS.md'] });
N('writing', 'organ', 'build', 'Writing transfer (M1 §161): cut the words that do no work', { status: 'INTEGRATION-TESTED', code: [S2 + '#wordwork'], tests: R('R23') });
N('lifelinks', 'organ', 'build', 'Life links (§107, M1 §163–166): medicine, acting, building, negotiation and the body as far-transfer targets', { status: 'INTEGRATION-TESTED', tests: R('R21', 'R14'), code: [S3A + '#chest pain'] });
N('language', 'organ', 'frontier', 'Language as a civilisation portal (§34): language learning that unlocks literature, humour, film and idiom', { status: 'DESIGNED', docs: [C3 + '02_ORGANS.md'] });
N('atscale', 'organ', 'frontier', 'Cultural possession at scale and organ breadth (§235, §16–25 "eventually"): thousands of works, every form and medium', { status: 'DESIGNED', docs: [C3 + '02_ORGANS.md'], deps: ['civgraph', 'masterpiece', 'compiler'] });
N('experiences', 'possession', 'build', 'The required production experiences (§216): masterpiece, science, mathematics, art, music, history, a cross-domain boss world, a salon', { status: 'INTEGRATION-TESTED', tests: V3('V6', 'V4').concat(R('R31')), code: [S3A + '#id: "km1"', S3B + '#id: "euler"', S3B + '#id: "willow"', S3B + '#id: "pattern"', S3B + '#id: "cadence"', S3C + '#id: "wisdom"', S3C + '#id: "salon"', S2 + '#id: "boss"'] });
N('season3', 'content', 'doc', 'Season 3 specification, content audit and the season tournament (§170)', { status: 'DESIGNED', docs: [D + '09_SEASON_3.md'] });
N('seasons', 'content', 'build', 'Seasons as optional internal structure (§171): only the bootloader keeps an order; the rest is compiled', { status: 'INTEGRATION-TESTED', tests: V3('C1', 'C2'), code: [ENG + '#z.boot'] });
N('crossseason', 'content', 'build', 'Cross-season and cross-cultural transfer (§172–173): old ideas return inside new sessions; no civilisation in isolation', { status: 'INTEGRATION-TESTED', tests: R('R14').concat(V3('C1', 'V3')), code: [ENG + '#rotate'] });

/* ── the engine and the learner model ── */
N('compiler', 'engine', 'build', 'Session compiler (§160, M2 §166, §171–172): gaps, errors, culture, rotation, the unknown and leverage, with reasons', { status: 'INTEGRATION-TESTED', code: [ENG + '#function choose(', ENG + '#const W ='], tests: V3('C1', 'C4').concat(R('R15')), docs: [C3 + '03_ENGINE.md'] });
N('sessionobj', 'engine', 'build', 'Session object (§161, M1 §184, M2 §167)', { status: 'INTEGRATION-TESTED', code: [ENG + '#function sessionObject('], tests: V3('C5') });
N('multiplex', 'engine', 'build', 'Multiplex learning without multiplex cheating (§36–37)', { status: 'INTEGRATION-TESTED', code: [ENG + '#function multiplex('], tests: V3('L3') });
N('fiv', 'engine', 'build', 'Functional-capability vector (§38, M1 §81)', { status: 'INTEGRATION-TESTED', code: [ENG + '#function vector('], tests: V3('L1') });
N('velocity', 'engine', 'build', 'Transformation velocity and acceleration (§45–46, M2 §149–150)', { status: 'INTEGRATION-TESTED', code: [ENG + '#function velocity('], tests: V3('L2') });
N('twin', 'engine', 'build', 'Cognitive digital twin (§163, M1 §78)', { status: 'INTEGRATION-TESTED', code: [ENG + '#function twin('], tests: V3('L5') });
N('laws', 'engine', 'build', 'Personal pedagogy genome and intellectual physics (§74–75): falsifiable rules about this learner, retested', { status: 'IMPLEMENTED', code: [ENG + '#function laws('] });
N('genome', 'engine', 'build', 'Human capability genome (§60): components, prerequisites, synergies, conflicts, transfer, evidence, cost, expressions, descendants, compounds', { status: 'INTEGRATION-TESTED', code: ['source/public/renaissance-genome.js#window.RENAISSANCE_GENOME', ENG + '#function genome('], tests: V3('G1', 'G2'), docs: [O + '05_GENOME_AND_ENGINES.md'] });
N('periodic', 'engine', 'build', 'Capability periodic table, cognitive chemistry, species and dark matter (§59, §61–63)', { status: 'INTEGRATION-TESTED', code: ['source/public/renaissance-genome.js#gaps:', 'source/public/renaissance-genome.js#const compounds'], tests: V3('G1') });
N('memory', 'engine', 'build', 'Memory without memory bureaucracy (§102): ideas return inside later sessions, interleaved', { status: 'INTEGRATION-TESTED', code: [ENG + '#function dueHooks('], tests: R('R10', 'R14', 'R18') });
N('gc', 'engine', 'build', 'Knowledge half-life, garbage collection and assimilation (§100–103)', { status: 'INTEGRATION-TESTED', code: [ENG + '#assimilated'], tests: V3('D4') });
N('scaffold', 'engine', 'build', 'Scaffold decay and anti-dependence (§104–105, M2 §69): unaided later answers, probes with every helper off', { status: 'INTEGRATION-TESTED', tests: R('R8', 'R14').concat(V3('P1')), code: [ENG + '#function dueProbes('] });
N('calib', 'engine', 'build', 'Reality calibration (§97, M1 §41, M2 §45): confidence on every answer and real-world forecasts scored later', { status: 'INTEGRATION-TESTED', code: [ENG + '#function calibration(', ENG + '#function forecastView('], tests: V3('F1').concat(R('R6', 'R7')) });
N('beliefs', 'engine', 'build', 'Belief version control (§95): what was held, with what confidence, and what replaced it', { status: 'INTEGRATION-TESTED', code: [ENG + '#st.beliefs.push'], tests: R('R29') });
N('contradiction', 'engine', 'build', 'Contradiction reactor (§96): unresolved questions stay open on the page', { status: 'IMPLEMENTED', code: [S3A + '#Open question'] });
N('immune', 'engine', 'build', 'Idea immune system (§93): strongest objection, counterexample, alternative model, scope for every important idea', { status: 'IMPLEMENTED', code: [S3A + '#kind: "counterexample"'] });
N('perspectives', 'engine', 'build', 'Perspective accelerator, thought interferometer, ideological immunity (M1 §36–37, M1 §109, M2 §133, M2 §140)', { status: 'IMPLEMENTED', code: [S3C + '#One idea, four listeners'] });
N('worldmodel', 'engine', 'build', 'World-model compiler and anti-monoculture (§98–99): matter to meaning, plural models kept', { status: 'DESIGNED', docs: [O + '05_GENOME_AND_ENGINES.md'] });
N('unknown', 'engine', 'build', 'Unknown-unknown and serendipity engines (§57–58): reserved capacity for what he would not choose', { status: 'INTEGRATION-TESTED', code: [ENG + '#unknown:'], tests: V3('C1', 'P3').concat(R('R31')) });
N('unknownconcept', 'engine', 'process', 'Unknown-concept engine (§56): named new abstractions kept only if they compress, predict, transfer', { status: 'UNIT-TESTED', tests: OM('O10'), docs: [O + '02_REGISTRY.md'] });
N('alien', 'measure', 'build', 'Alien problem suite (§42, §121): a sealed unknown problem each week from day 7', { status: 'ADVERSARIALLY-TESTED', code: [ENG + '#function probeDue('], tests: V3('P3', 'P4', 'S2') });
N('sealed', 'measure', 'guard', 'Sealed transfer and the leak firewall (§43, §154): no item text in content, metadata, names, order or logs', { status: 'ADVERSARIALLY-TESTED', code: ['tools/renaissance/seal.js#function build', ENG + '#function unseal('], tests: V3('S1', 'S2', 'P2') });
N('geniusdelta', 'measure', 'build', 'Genius-delta battery (§44, M1 §208): parallel forms at day 0, 30 and 90', { status: 'ADVERSARIALLY-TESTED', code: [ENG + '#function probeReport('], tests: V3('P1', 'P2', 'P3', 'S1') });
N('counterfeit', 'measure', 'guard', 'Counterfeit-genius, polymath-theatre and adversarial-guessing tests (§147, §149, §152–153)', { status: 'ADVERSARIALLY-TESTED', tests: R('R35').concat(V3('S3')), code: ['tests/renaissance_v3_test.js#firstShown'] });
N('gaming', 'measure', 'doc', 'Benchmark gaming (§151, M2 §129, M2 §143): a cheat and a guard for every metric', { status: 'IMPLEMENTED', docs: [O + '04_OBJECTIVE_AND_METRICS.md'] });
N('hostile', 'measure', 'doc', 'Hostile test universe and matrix (§155, M1 §124, M1 §205)', { status: 'DESIGNED', docs: [C3 + '04_MEASUREMENT.md'] });
N('benchlab', 'measure', 'doc', 'Benchmark laboratory, universe, equal-time, horizons, dimensions, masterpiece benchmark (§141–145)', { status: 'IMPLEMENTED', docs: [D + '05_BENCHMARKS.md', C3 + '04_MEASUREMENT.md'] });
N('empirical', 'measure', 'build', 'Empirical future queue (§193–194): 30, 60, 90 days, 6 and 12 months, items sealed before exposure', { status: 'ADVERSARIALLY-TESTED', code: [ENG + '#function dueProbes('], tests: V3('P3', 'P5', 'S1'), docs: [CP + 'EMPIRICAL_QUEUE.md'] });
N('observability', 'measure', 'principle', 'Genius must be observable in performance, not compliments (§39, §233–234)', { status: 'IMPLEMENTED', tests: V3('P5', 'L1'), docs: [D + '05_BENCHMARKS.md'] });

/* ── self-improvement ── */
N('L1', 'self', 'build', 'L1 representation order (the picture chooser)', { status: 'INTEGRATION-TESTED', code: [ENG + '#function govState('], tests: R('R36', 'R37') });
N('L2', 'self', 'build', 'L2 step order trial', { status: 'INTEGRATION-TESTED', code: [ENG + '#L2: { level: 2'], tests: V3('E1', 'E2') });
N('L3', 'self', 'build', 'L3 step length trial', { status: 'INTEGRATION-TESTED', code: [ENG + '#L3: { level: 3'], tests: V3('E1') });
N('L4', 'self', 'build', 'L4 session length trial', { status: 'DESIGNED' });
N('L5', 'self', 'build', 'L5 difficulty trial (a second way offered before answering)', { status: 'INTEGRATION-TESTED', code: [ENG + '#L5: { level: 5'], tests: V3('E1') });
N('L6', 'self', 'build', 'L6 retrieval interval trial', { status: 'INTEGRATION-TESTED', code: [ENG + '#L6: { level: 6'], tests: V3('E1') });
N('L7', 'self', 'build', 'L7 task type trial', { status: 'DESIGNED' });
N('L8', 'self', 'build', 'L8 source mix trial', { status: 'DESIGNED' });
N('L9', 'self', 'build', 'L9 session architecture trial', { status: 'DESIGNED' });
N('L10', 'self', 'build', 'L10 season order trial (compiler against the written order)', { status: 'INTEGRATION-TESTED', code: [ENG + '#L10: { level: 10'], tests: V3('C2', 'E1') });
N('L11', 'self', 'build', 'L11 capability priority trial', { status: 'DESIGNED' });
N('L12', 'self', 'build', 'L12 curriculum generation strategy', { status: 'DESIGNED' });
N('L13', 'self', 'build', 'L13 pedagogy generation strategy', { status: 'DESIGNED' });
N('L14', 'self', 'build', 'L14 meta-pedagogy: the judge is judged (rollback of an adopted arm that later loses, caution ×1.5)', { status: 'INTEGRATION-TESTED', code: [ENG + '#caution'], tests: V3('E4') });
N('safeexp', 'self', 'build', 'Safe experimentation (§71, §73): baseline control, minimum sample, rollback, no-harm floor, a clear metric', { status: 'INTEGRATION-TESTED', code: [ENG + '#const EXPCFG'], tests: V3('E1', 'E3', 'E4') });
N('selfimprove', 'self', 'rollup', 'Self-improving curriculum, pedagogy, meta and meta-meta pedagogy (§123–126, §295, M2 §90–98)', { deps: ['L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9', 'L10', 'L11', 'L12', 'L13', 'L14', 'safeexp', 'tournament'] });
N('noselfgrant', 'self', 'guard', 'Self-improvement never self-grants authority; no unsafe autonomous real-world action (§248–249)', { status: 'IMPLEMENTED', code: [ENG + '#armOf'], docs: [C3 + '03_ENGINE.md'] });
N('autophagy', 'self', 'build', 'Renaissance eats its own curriculum (§243–244): assimilated drills retire; weak designs are superseded', { status: 'INTEGRATION-TESTED', tests: V3('D4'), code: [ENG + '#assimilated'] });
N('tournament', 'self', 'doc', 'Tournaments (§140, §179, §224–225, M1 §216): experience, explanation, primary-text and idea tournaments with the losers named', { status: 'DESIGNED', docs: [D + '09_SEASON_3.md'] });

/* ── research, invention, lineage ── */
N('registry', 'research', 'process', 'The 1,003-mechanism registry, searched before inventing, not frozen, without redundancy (§177–180, M1 §127–133, M2 §100–126)', { status: 'UNIT-TESTED', tests: OM('O1', 'O2', 'O3', 'O4', 'O5', 'O6', 'O7', 'O8', 'O9', 'O10', 'O11'), docs: [O + '02_REGISTRY.md', D + '04_INVENTION_REGISTRY.md'] });
N('research', 'research', 'doc', 'Research outputs and the actual problem (§132–133, M1 §138, M1 §201, M2 §1, M2 §158)', { status: 'IMPLEMENTED', docs: [D + '01_RESEARCH.md'] });
N('priorart', 'research', 'process', 'Prior-art attack (§131, M2 §160): every new mechanism labelled KNOWN, COMBO or UNCLEAR with its ancestor', { status: 'UNIT-TESTED', tests: OM('O7'), docs: [O + '02_REGISTRY.md'] });
N('originality', 'research', 'process', 'Originality and invention without nonsense (§53, M1 §82, M1 §135, M1 §137)', { status: 'UNIT-TESTED', tests: OM('O7'), docs: [D + '04_INVENTION_REGISTRY.md'] });
N('ontology', 'research', 'doc', 'Ontology escape and making Renaissance obsolete (§129–130, §281, M2 §99, M2 §124–126, M2 §177–179)', { status: 'IMPLEMENTED', docs: [O + '02_REGISTRY.md', D + '04_INVENTION_REGISTRY.md'] });
N('objective', 'research', 'doc', 'Objective evolution (§128, M2 §84, M2 §128)', { status: 'IMPLEMENTED', docs: [O + '04_OBJECTIVE_AND_METRICS.md'] });
N('lineage', 'research', 'doc', 'Prompt evolution: mission v2, v3 and the final evolved mission for ABSOLUTE COMPLETION (§127, §258, §50 of §214)', { status: 'DESIGNED', docs: [C3 + '06_MISSION_LINEAGE.md'] });
N('principles14', 'research', 'doc', 'The 14 principles recovered and retested against the new requirements, with the compression test (§181–182, §254)', { status: 'DESIGNED', docs: [C3 + '06_MISSION_LINEAGE.md'] });
N('redteam', 'research', 'doc', 'Final red team, unknown-unknown grand pass, donor rule, what Opus would miss, the meta questions (§250–259, §278–281)', { status: 'DESIGNED', docs: [C3 + '06_MISSION_LINEAGE.md'] });
N('principles', 'research', 'principle', 'The confusions and final principles (§198–208, §288–298): dignity, joy, beauty, rigour, taste, truth…, each with its enforcing guard', { status: 'DESIGNED', docs: [C3 + '06_MISSION_LINEAGE.md'] });
N('northstar', 'research', 'doc', 'North star, transformation goal and final command (§1, §49–50, §286–287, §300, M1 §0–1, M1 §220, M1 §225, M2 §183)', { status: 'IMPLEMENTED', docs: [O + '04_OBJECTIVE_AND_METRICS.md'] });
N('arch', 'research', 'doc', 'Required architecture and implementation path (M1 §203, M1 §213)', { status: 'IMPLEMENTED', docs: [D + '03_ARCHITECTURE.md'] });
N('omegadeliv', 'research', 'doc', 'OMEGA final deliverables and status labels (M2 §180–181)', { status: 'IMPLEMENTED', docs: [O + '00_README.md'] });
N('asymmetry', 'research', 'principle', 'Machine effort asymmetry and source search (§222–223, M1 §83, M2 §14)', { status: 'IMPLEMENTED', tests: V3('V5'), docs: [D + '10_MASTERPIECE_COMPILER.md'], evidence: 'Every quotation checked by the machine; the reader gets one record.' });
N('faculty', 'research', 'process', 'Ephemeral genius faculty and teacher generator (M1 §84–85): simulated great minds as teachers', { status: 'REJECTED-WITH-REASON', reason: 'Simulated speech put in the mouths of real people is fabricated quotation (§136). Replaced by registered quotations in their scenes and dialogue built only from attributed lines (quotes, V5).' });
N('canon', 'research', 'process', 'Personal canon market and anti-canon (M1 §28–29, M2 §79–80)', { status: 'MERGED', sup: 'compiler', reason: 'The compiler already prices works for this learner (unpossessed works, leverage, dependants); the anti-canon lives in the possession ladder\'s criticism rung (hostile verdicts such as Nabokov\'s).' });
N('zoom', 'research', 'process', 'Scale switching, time-scale switching and model zoom (M1 §151–153)', { status: 'MERGED', sup: 'reps', reason: 'Implemented as representations: the log scale (doubling), the map versus the graph (Königsberg), the overhead view (film); SHOW ME DIFFERENTLY switches them.' });
N('possibility', 'research', 'empirical', 'Human possibility engine, optionality and possible futures (M1 §80, M1 §101–103, M1 §169–170, M1 §219, M2 §81–83)', { status: 'SPECIFIED', docs: [D + '05_BENCHMARKS.md'], due: 'years', evidence: 'P(t) protocol written; needs real life outcomes over years.' });
N('frontierradar', 'research', 'build', 'Frontier radar and knowledge recompiler (M1 §105–106, M2 §74–75, §133): time-sensitive claims re-verified on a half-life', { status: 'DESIGNED' });
N('development', 'research', 'principle', 'Developmental enrichment without neuromyths; no brain-hack nonsense (§47–48)', { status: 'DESIGNED', docs: [C3 + '04_MEASUREMENT.md'] });
N('longitudinal', 'research', 'doc', 'Longitudinal simulation Day 1 → Year 20 and mature life; lifetime phases; civilisational delta (§51–52, §167–168, M1 §168, M1 §171, M2 §170)', { status: 'PROTOTYPED', docs: [D + '06_LONGITUDINAL.md', C3 + '04_MEASUREMENT.md'], evidence: 'Year 10 exists; Year 20 and mature life to be added.' });
N('uberbond', 'future', 'doc', 'UberBond coupling, capability donation and the two-way question (§108–110, M1 §165)', { status: 'DESIGNED', docs: [C3 + '05_RIGHTS_MEDIA_FUTURE.md'] });
N('exocortex', 'future', 'doc', 'Exocortex architecture and the division of cognition (§111, M1 §191–193)', { status: 'DESIGNED', docs: [C3 + '05_RIGHTS_MEDIA_FUTURE.md'] });
N('futureiface', 'future', 'doc', 'Future human-machine continuum (§112, §245)', { status: 'DESIGNED', docs: [C3 + '05_RIGHTS_MEDIA_FUTURE.md'], deps: ['device'] });
N('neuralsafety', 'future', 'doc', 'Neural safety constitution (§113)', { status: 'DESIGNED', docs: [C3 + '05_RIGHTS_MEDIA_FUTURE.md'] });
N('providerneutral', 'future', 'principle', 'Provider neutrality (§246, M2 §142): the architecture, not a model supplier, is the system', { status: 'IMPLEMENTED', docs: [C3 + '05_RIGHTS_MEDIA_FUTURE.md'] });
N('compounding', 'engine', 'build', 'Compound interest machinery (§211, §237–242, §294): shared context and prerequisites make later works cheaper', { status: 'INTEGRATION-TESTED', code: [ENG + '#leverage:'], tests: V3('C1', 'V2') });
N('first90', 'engine', 'build', 'First 90-day acceleration (§120): high-leverage primitives front-loaded (the bootloader), measured at day 30 and 90', { status: 'INTEGRATION-TESTED', tests: V3('C1', 'P3'), code: [ENG + '#bootloader'] });
N('socialfeedback', 'engine', 'build', 'Real social feedback (§232): after a conversation session, a private tap on whether real talk revealed gaps, questions or success', { status: 'DESIGNED' });
N('critics', 'content', 'doc', 'Experience critic panel (§221): domain, pedagogy, sceptic, beginner, cultural critic, UX lenses per major experience', { status: 'DESIGNED', docs: [D + '09_SEASON_3.md'] });
N('qualityfloor', 'content', 'rollup', 'Quality floor for every shipped experience (§219)', { deps: ['nohalluc', 'provenance', 'rights', 'a11y', 'sealed', 'counterfeit', 'arc', 'oatmeal', 'mq'] });

/* ── the completion machinery, process and delivery ── */
N('oracle', 'completion', 'build', 'Coverage oracle, requirement graph, zero silent omissions, the gap loop (§3–5, §184–185, §250, §266–267, §271, §299)', { status: 'DESIGNED', code: ['tools/renaissance/oracle.js#function run('] });
N('ledger', 'completion', 'build', 'Completion ledger, the two meanings of 100%, no fake 100% (§6–7, §191–192, §277, M1 §115, M2 §173)', { status: 'DESIGNED', code: ['tools/renaissance/oracle.js#function ledger('] });
N('artifacts', 'completion', 'doc', 'The 50 required artifacts (§214), each located', { status: 'DESIGNED', docs: [C3 + '00_README.md'] });
N('implement', 'completion', 'process', 'Implementation law: implementable requirements are code, not markdown; no fake placeholders (§215, §218, §260–261, M1 §176, M2 §156–157)', { status: 'DESIGNED' });
N('continuity', 'completion', 'process', 'Do not start over; preserve registry, seasons and fixes; no amputation (§0, §183, §272, M1 §218, M2 §159)', { status: 'INTEGRATION-TESTED', tests: R('R35', 'R21').concat(OM('O2')), docs: ['docs/RENAISSANCE/README.md'], evidence: 'All 38 season 1–2 checks and the 11 registry checks still pass on the current head; the longest-answer fix holds (R35).' });
N('autonomy', 'completion', 'process', 'No routine founder labour; escalate only genuine blockers; no re-asking (§187, §273–275, M1 §214–215)', { status: 'IMPLEMENTED', docs: [C3 + '06_MISSION_LINEAGE.md'] });
N('blockers', 'completion', 'process', 'Blocker discipline (§186): only real external blockers, each documented with its preparatory work', { status: 'DESIGNED' });
N('receipts', 'completion', 'process', 'Receipts for every completion claim (§190)', { status: 'DESIGNED', docs: ['receipts/v18_1/full_regression.log'] });
N('deploy', 'completion', 'process', 'Deployment through an authorised path, verified (§188)', { status: 'DESIGNED' });
N('merge', 'completion', 'process', 'Branch and merge policy (§189): no failing work merged, rollback preserved', { status: 'IMPLEMENTED', evidence: 'Work is committed on the designated branch and pushed; this session\'s repository policy forbids opening a pull request unless the owner asks, so nothing is merged; every step is a revertible commit.' });
N('report', 'completion', 'doc', 'Completion report (§276)', { status: 'DESIGNED', docs: [CP + 'COMPLETION_REPORT.md'] });
N('declarations', 'completion', 'process', 'Declarations only when criteria are met (§209–213, §282–284, M1 §2, M1 §173–175, M1 §222, M2 §155, M2 §175–176, M2 §182)', { status: 'DESIGNED', docs: [CP + 'COMPLETION_REPORT.md'] });

/* ── empirical validation (never closed by code) ── */
const E = (id, name, due, deps, protocol) => N(id, 'empirical', 'empirical', name, { status: 'SPECIFIED', due, deps, docs: [CP + 'EMPIRICAL_QUEUE.md'], evidence: protocol });
E('e-hooks30', 'Delayed unaided recall at 30 days (first hooks of seasons 1–3)', '2026-10-26', ['memory'], 'Hook records with gap ≥ 30 days; report rate with n.');
E('e-formB', 'Parallel form B at day 30 against form A at day 0', 'day 30 after first open', ['geniusdelta'], 'Sealed forms; raw scores with n; no composite.');
E('e-formA90', 'Form A repeated at day 90 (genius delta)', 'day 90 after first open', ['geniusdelta'], 'Same items as day 0, sealed; change with n and chance level.');
E('e-alien12', 'Twelve weekly unknown problems: orientation over weeks 1–12', 'day 84', ['alien'], 'Orientation dimension of the vector; slope once ≥ 3 weeks of ≥ 5 answers.');
E('e-rt', 'Reader Turing questions on The Brothers Karamazov', '30 days after km3', ['readerturing'], 'Twelve sealed items; possession rung 12 needs ≥ 8 answers at ≥ 75%.');
E('e-velocity', 'Transformation velocity and acceleration', '6 weeks of data (acceleration)', ['velocity'], 'Weekly slope of delayed unaided accuracy; acceleration after six weeks.');
E('e-trials', 'Trial verdicts for L1–L14 (adopt, drop, harm)', 'as samples reach their minimum', ['selfimprove'], 'Each trial judged on its own minimum sample and margin; nothing is adopted before.');
E('e-calib', 'Real-world forecast calibration', 'after five checked forecasts', ['calib'], 'Brier score of forge forecasts against reported use.');
E('e-bench', 'Equal-time benchmarks against reading, summaries, textbooks and tutors', 'after the exam (Nov 2026) and at 6 and 12 months', ['benchlab'], 'Protocol in 05_BENCHMARKS; needs real sessions of the alternatives.');
E('e-compound', 'Compounding: later works and domains cost less time to possess', '6 and 12 months', ['compounding'], 'Minutes to reach a possession rung, per work, over time.');
E('e-year', 'Six- and twelve-month transformation (functional vector, possession, real use)', '2027-03 and 2027-09', ['fiv', 'possession', 'realitybridge'], 'Longitudinal protocol; raw scores with n.');

/* ── registry pass themes → the node that owns each theme's candidates (§3, §177) ── */
const themes = {
  1: 'fiv', 2: 'wormholes', 3: 'compiler', 4: 'arc', 5: 'memory', 6: 'gc', 7: 'tournament', 8: 'safeexp', 9: 'question', 10: 'masterpiece', 11: 'memory', 12: 'compiler', 13: 'compiler', 14: 'device', 15: 'discovery', 16: 'intuition', 17: 'boss', 18: 'reps', 19: 'art', 20: 'music', 21: 'architecture', 22: 'dose', 23: 'claims', 24: 'curiosity', 25: 'reps', 26: 'memory', 27: 'math', 28: 'philosophy', 29: 'global', 30: 'history', 31: 'sovereignty', 32: 'civgraph', 33: 'controls', 34: 'futureiface', 35: 'calib', 36: 'wormholes', 37: 'unknown', 38: 'laws', 39: 'registry', 40: 'ontology',
  41: 'inside', 42: 'primary', 43: 'vocab', 44: 'satisfaction', 45: 'civgraph', 46: 'genome', 47: 'newsense', 48: 'reps', 49: 'prereq', 50: 'wormholes', 51: 'discovery', 52: 'alien', 53: 'question', 54: 'beliefs', 55: 'perspectives', 56: 'gc', 57: 'taste', 58: 'creation', 59: 'twin', 60: 'scaffold', 61: 'boss', 62: 'unknown', 63: 'possibility', 64: 'stoprule', 65: 'selfimprove', 66: 'wormholes', 67: 'science', 68: 'lifelinks', 69: 'readerturing', 70: 'science', 71: 'dose', 72: 'recovery',
};
module.exports = { nodes, themes };
