// Sealed measurement items (§43, §154, §194): seal, verify and audit.
//   node tools/renaissance/seal.js build <plaintext.json>   seal items into source/public/renaissance-sealed.js and
//                                                          write the pre-registration (hashes) in docs/RENAISSANCE/sealed/
//   node tools/renaissance/seal.js verify                  decode the sealed file and check every hash against the
//                                                          pre-registration (any change after registration fails)
// Sealing is obfuscation plus pre-registration, not secrecy: the items ship to the learner's device. It stops the
// items being read by accident (view-source, logs, file names, diffs) and makes any later edit detectable. The
// plaintext is never committed; the only readable copy is recovered from the sealed file with this tool.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'source/public/renaissance-sealed.js');
const REG = path.join(ROOT, 'docs/RENAISSANCE/sealed/preregistration.json');
const SALT = 'renaissance-sealed/2026-09-26';

// the same FNV-1a hash as renaissance-v1.js (hashNum), over UTF-16 code units
function hashNum(str) {
  let h = 2166136261;
  for (const ch of String(str)) h = Math.imul(h ^ ch.charCodeAt(0), 16777619) >>> 0;
  return h;
}
function xor(bytes, salt, id) {
  let h = hashNum(salt + ':' + id);
  const out = Buffer.alloc(bytes.length);
  for (let i = 0; i < bytes.length; i++) {
    h = (Math.imul(h ^ (h >>> 15), 2246822507) + 3266489909 + i) >>> 0;
    out[i] = bytes[i] ^ (h & 255);
  }
  return out;
}
const seal = (obj, salt) => xor(Buffer.from(JSON.stringify(obj.q), 'utf8'), salt, obj.id).toString('base64');
const unsealQ = (blob, id, salt) => JSON.parse(xor(Buffer.from(blob, 'base64'), salt, id).toString('utf8'));
const sha = (s) => crypto.createHash('sha256').update(s).digest('hex');
// the canonical text that is hashed: metadata and the question, in a fixed key order
const canon = (it) => JSON.stringify({ id: it.id, form: it.form, at: it.at, after: it.after || null, cov: it.cov || null, atoms: it.atoms || [], q: it.q });

function loadSealed() {
  const g = {};
  new Function('window', fs.readFileSync(OUT, 'utf8'))(g);
  return g.RENAISSANCE_SEALED;
}
function decodeAll() {
  const S = loadSealed();
  return S.items.map((m) => Object.assign({}, m, { q: unsealQ(m.blob, m.id, S.salt) }));
}

if (require.main === module) {
  const [cmd, file] = process.argv.slice(2);
  if (cmd === 'build') {
    const items = JSON.parse(fs.readFileSync(file, 'utf8'));
    const meta = items.map((it) => {
      const m = { id: it.id, form: it.form, at: it.at, order: it.order || 0, blob: seal(it, SALT) };
      if (it.after) m.after = it.after;
      // coverage and atoms travel inside a second sealed field so the visible metadata says nothing about content
      m.meta = xor(Buffer.from(JSON.stringify({ cov: it.cov || null, atoms: it.atoms || [] }), 'utf8'), SALT + '/meta', it.id).toString('base64');
      return m;
    });
    const js = '/* RENAISSANCE · sealed measurement items. Generated by tools/renaissance/seal.js; do not edit by hand.\n * Pre-registered in docs/RENAISSANCE/sealed/ (sha-256 of each item). Opened only on the day an item is due. */\n' +
      'window.RENAISSANCE_SEALED = ' + JSON.stringify({ v: 1, salt: SALT, registered: new Date().toISOString().slice(0, 10), items: meta }) + ';\n';
    fs.writeFileSync(OUT, js);
    const reg = { registered: new Date().toISOString(), salt: SALT, rule: 'Items were written before any learner answered them and before any comparison. Changing an item changes its hash and fails tests/renaissance_v3_test.js.', items: items.map((it) => ({ id: it.id, form: it.form, at: it.at, after: it.after || null, sha256: sha(canon(it)) })) };
    fs.mkdirSync(path.dirname(REG), { recursive: true });
    fs.writeFileSync(REG, JSON.stringify(reg, null, 1) + '\n');
    console.log('sealed', items.length, 'items →', path.relative(ROOT, OUT));
  } else if (cmd === 'verify') {
    const reg = JSON.parse(fs.readFileSync(REG, 'utf8'));
    const S = loadSealed();
    const bad = [];
    for (const r of reg.items) {
      const m = S.items.find((x) => x.id === r.id);
      if (!m) { bad.push(r.id + ' missing'); continue; }
      const q = unsealQ(m.blob, m.id, S.salt);
      const meta = JSON.parse(xor(Buffer.from(m.meta, 'base64'), S.salt + '/meta', m.id).toString('utf8'));
      const h = sha(canon({ id: m.id, form: m.form, at: m.at, after: m.after, cov: meta.cov, atoms: meta.atoms, q }));
      if (h !== r.sha256) bad.push(r.id + ' changed after registration');
    }
    console.log(bad.length ? 'FAIL ' + bad.join('; ') : 'OK ' + reg.items.length + ' items match their registration');
    process.exit(bad.length ? 1 : 0);
  } else console.log('usage: seal.js build <plaintext.json> | verify');
}
module.exports = { hashNum, xor, unsealQ, decodeAll, loadSealed, canon, sha, SALT, REG, OUT };
