// Encrypt the prepared department drawings for the public site (AES-256-GCM, one random IV per file).
// Usage: IX_DEPT_KEY=<kid>.<base64url 32-byte key> node scripts/dept-figs/encrypt.mjs <prepared_dir>
// Writes source/public/dept/<id>.bin (IV ‖ ciphertext ‖ tag, the layout WebCrypto decrypts) and the
// manifest source/public/dept-figs-v16-data.js. The key is never written into the repo: the owner's
// app receives it once through a link (#ixk=<kid>.<key>) and keeps it in the synced, private state.
import { createCipheriv, randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const [kid, k64] = String(process.env.IX_DEPT_KEY || "").split(".");
const key = Buffer.from(k64 || "", "base64url");
if (!/^k\d+$/.test(kid || "") || key.length !== 32) throw new Error("IX_DEPT_KEY must be <kid>.<base64url 32-byte key>");
const src = process.argv[2];
if (!src) throw new Error("usage: encrypt.mjs <prepared_dir>");

const seal = (buf) => {
  const iv = randomBytes(12),
    c = createCipheriv("aes-256-gcm", key, iv),
    body = Buffer.concat([c.update(buf), c.final()]);
  return Buffer.concat([iv, body, c.getAuthTag()]);
};
const jpegSize = (b) => {
  // width/height from the SOF marker
  for (let i = 2; i < b.length; ) {
    const m = b[i + 1],
      len = b.readUInt16BE(i + 2);
    if (m >= 0xc0 && m <= 0xcf && m !== 0xc4 && m !== 0xc8 && m !== 0xcc) return { h: b.readUInt16BE(i + 5), w: b.readUInt16BE(i + 7) };
    i += 2 + len;
  }
  return { w: 0, h: 0 };
};

const map = JSON.parse(readFileSync(join(here, "map.json"), "utf8"));
const out = join(root, "source", "public", "dept");
mkdirSync(out, { recursive: true });
for (const f of readdirSync(out)) if (f.endsWith(".bin")) unlinkSync(join(out, f));
const figs = [];
for (const f of map.figs) {
  const buf = readFileSync(join(src, f.id + ".jpg"));
  writeFileSync(join(out, f.id + ".bin"), seal(buf));
  const { w, h } = jpegSize(buf);
  figs.push({ id: f.id, sec: f.sec, cap: f.cap, w, h, src: f.pdf });
}
const data = { kid, probe: seal(Buffer.from("intellectuality-dept-ok")).toString("base64"), figs };
writeFileSync(
  join(root, "source", "public", "dept-figs-v16-data.js"),
  "/* Generated by scripts/dept-figs/encrypt.mjs: the encrypted department drawings (dept/<id>.bin) and where each is taught. */\n" +
    "window.INTELLECTUALITY_DEPT_FIGS = " + JSON.stringify(data) + ";\n",
);
console.log("encrypted", figs.length, "drawings with key", kid);
