// Publish the prepared department drawings, Kasr Al Ainy book figures and Dr Sameh Doss's labelled drawings as plain JPEGs. v18.6: the owner asked
// (27 Sep 2026) for the lock to be removed so they show like every other picture, with no key or link.
// Usage: node scripts/dept-figs/publish.mjs <prepared_dir>
// Copies <id>.jpg into source/public/dept/ and writes the manifest source/public/dept-figs-v16-data.js.
// (encrypt.mjs is the earlier, key-locked way of publishing the same set.)
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const src = process.argv[2];
if (!src) throw new Error("usage: publish.mjs <prepared_dir>");
const jpegSize = (b) => {
  // width/height from the SOF marker
  for (let i = 2; i < b.length; ) {
    const m = b[i + 1],
      len = b.readUInt16BE(i + 2);
    if (m >= 0xc0 && m <= 0xcf && m !== 0xc4 && m !== 0xc8 && m !== 0xcc) return { h: b.readUInt16BE(i + 5), w: b.readUInt16BE(i + 7) };
    i += 2 + len;
  }
  return { w: 0, h: 0 };
};

const map = JSON.parse(readFileSync(join(here, "map.json"), "utf8"));
const out = join(root, "source", "public", "dept");
mkdirSync(out, { recursive: true });
for (const f of readdirSync(out)) if (f.endsWith(".bin") || f.endsWith(".jpg")) unlinkSync(join(out, f));
const figs = [];
for (const f of map.figs) {
  const buf = readFileSync(join(src, f.id + ".jpg"));
  writeFileSync(join(out, f.id + ".jpg"), buf);
  const { w, h } = jpegSize(buf);
  figs.push({ id: f.id, sec: f.sec, ...(f.sc ? { sc: f.sc } : {}), cap: f.cap, ...(f.ans ? { ans: f.ans } : {}), ...(f.drill ? { drill: f.drill } : {}), ...(f.book ? { book: f.book } : {}), ...(f.sameh ? { sameh: f.sameh } : {}), w, h, src: f.pdf });
}
writeFileSync(
  join(root, "source", "public", "dept-figs-v16-data.js"),
  "/* Generated by scripts/dept-figs/publish.mjs: the department drawings and Kasr Al Ainy book figures (dept/<id>.jpg) and where each is taught. */\n" +
    "window.INTELLECTUALITY_DEPT_FIGS = " + JSON.stringify({ plain: true, figs }) + ";\n",
);
console.log("published", figs.length, "drawings as plain JPEGs");
