#!/usr/bin/env python3
"""Write manifests/V14_2_CANDIDATE_MANIFEST.json + V14_2_SHA256SUMS.txt for the current source/ tree,
marking each deploy file as unchanged/modified/added against the v53 manifest."""
import hashlib, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; SRC = ROOT / "source"
v53 = json.loads((ROOT / "manifests/CURRENT_EXACT_SOURCE_MANIFEST.json").read_text())
base = {f["path"]: f["sha256"] for f in v53["files"]}
EXCLUDE = {"AGENTS.md": "platform-generated by Hatchable on read/deploy; not part of the deploy set (also absent from the v53 manifest)"}
files = []
for p in sorted(SRC.rglob("*")):
    if not p.is_file(): continue
    rel = p.relative_to(SRC).as_posix()
    if rel in EXCLUDE: continue
    b = p.read_bytes(); h = hashlib.sha256(b).hexdigest()
    files.append({"path": rel, "size": len(b), "sha256": h, "vs_v53": "unchanged" if base.get(rel) == h else ("modified" if rel in base else "added")})
man = {"project_id": v53["project_id"], "slug": v53["slug"], "candidate_version": "14.2", "based_on_deployment_version": 53,
       "status": "NOT DEPLOYED — candidate package (no Hatchable access from the build session)", "file_count": len(files),
       "excluded": EXCLUDE, "changed_vs_v53": [f["path"] for f in files if f["vs_v53"] != "unchanged"], "files": files}
(ROOT / "manifests/V14_2_CANDIDATE_MANIFEST.json").write_text(json.dumps(man, indent=1) + "\n")
(ROOT / "manifests/V14_2_SHA256SUMS.txt").write_text("".join(f"{f['sha256']}  {f['path']}\n" for f in files))
for f in files:
    if f["vs_v53"] != "unchanged": print(f["vs_v53"], f["path"], f["size"], f["sha256"])
