// Generates source/public/lesson-relevance-v15.js: for every lesson, its most related lessons
// (TF-IDF cosine over what the app teaches for it: LEARN note sections, professor teach lines,
// deep notes, lesson facts and topic). Used by the calendar spread (v15.2) to put a missed lesson
// next to the upcoming lesson it matters most for. Deterministic; re-run when notes change.
// Usage: node tests/serve.js source/public 8787 & node scripts/gen_lesson_relevance.js
const fs = require('fs');
const path = require('path');
const { open } = require('../tests/harness');
(async () => {
  const s = await open({ time: '2026-09-23T10:00:00+03:00', state: null, settle: 1200 });
  const out = await s.page.evaluate(() => {
    const STOP = new Set('the of and a an to in is are by for with from on at as or its it this that which be into than their all one not also very what where when how why who there here they them then because due called known found seen each other these those may can will does do has have been being was were more most less least both only same different between through within along near onto upon over under via picture trap kasr answer question lesson exam draw mark marks source bank tutor model first then side lateral medial anterior posterior superior inferior upper lower left right part parts main type types small large human'.split(' '));
    const stem = (w) => (w.length > 4 ? w.replace(/ies$/, 'y').replace(/(ae|es|s|um|us|on|a|i|e)$/, '') : w).slice(0, 8);
    const toks = (t) => String(t || '').toLowerCase().replace(/\*\*/g, '').replace(/fibre/g, 'fiber').replace(/[^a-z0-9]+/g, ' ').split(' ').filter((w) => w.length > 3 && !STOP.has(w)).map(stem);
    const flat = (x) => (x == null ? [] : Array.isArray(x) ? x.flatMap(flat) : typeof x === 'object' ? Object.values(x).flatMap(flat) : [String(x)]);
    const lessons = new Map();
    for (const d of COURSE.days) for (const l of d.lessons || []) if (!lessons.has(l.id)) lessons.set(l.id, l);
    const ids = [...lessons.keys()].sort();
    const P = window.INTELLECTUALITY_PROFESSOR || {}, D = window.INTELLECTUALITY_DEEP || {};
    const chapters = window.INTELLECTUALITY_LEARN_NOTES?.chapters || [];
    const docs = {};
    for (const id of ids) {
      const l = lessons.get(id), f = [l.topic, l.topic, l.objective, ...flat(l.facts), l.mental, l.draw];
      f.push(...flat(P[id]?.teach), P[id]?.mental || '', ...flat(D[id]?.deep));
      for (const c of chapters) if ((c.lessons || []).includes(id)) for (const x of c.s || []) if (!x.l || x.l === id) f.push(x.h, x.h, ...(x.p || []), ...(x.pic || []), ...(x.pic || []));
      docs[id] = toks(f.join(' '));
    }
    const df = {};
    for (const id of ids) for (const w of new Set(docs[id])) df[w] = (df[w] || 0) + 1;
    const N = ids.length;
    const vec = {};
    for (const id of ids) {
      const v = {};
      for (const w of docs[id]) v[w] = (v[w] || 0) + 1;
      let n = 0;
      for (const w in v) { v[w] = (1 + Math.log(v[w])) * Math.log(N / df[w]); n += v[w] ** 2; }
      n = Math.sqrt(n) || 1;
      for (const w in v) v[w] /= n;
      vec[id] = v;
    }
    const cos = (a, b) => { let d = 0; for (const w in a) if (b[w]) d += a[w] * b[w]; return d; };
    const rel = {};
    for (const a of ids) {
      const row = ids.filter((b) => b !== a).map((b) => [b, +cos(vec[a], vec[b]).toFixed(3)]).filter((x) => x[1] >= 0.02).sort((x, y) => y[1] - x[1]).slice(0, 14);
      rel[a] = Object.fromEntries(row);
    }
    return { rel, topics: Object.fromEntries(ids.map((id) => [id, lessons.get(id).subject.slice(0, 4) + ' · ' + lessons.get(id).topic])) };
  });
  await s.close();
  const body = '/* INTELLECTUALITY v15.2 · lesson relevance (generated by scripts/gen_lesson_relevance.js; do not edit).\n' +
    ' * rel[A][B] = TF-IDF cosine between what the app teaches for lessons A and B (LEARN notes, professor,\n' +
    ' * deep notes, facts). Top 14 per lesson, cosine >= 0.02. Used to place a missed lesson next to the\n' +
    ' * upcoming lesson it matters most for. */\nwindow.INTELLECTUALITY_LESSON_RELEVANCE = ' + JSON.stringify(out.rel) + ';\n';
  fs.writeFileSync(path.join(__dirname, '..', 'source', 'public', 'lesson-relevance-v15.js'), body);
  const show = ['T001', 'T002', 'T003', 'T004', 'T005', 'T006', 'T007', 'T008'];
  for (const a of show) console.log(a, out.topics[a], '→', Object.entries(out.rel[a]).slice(0, 6).map(([b, v]) => b + ' ' + out.topics[b].slice(7, 34) + ' ' + v).join(' | '));
  console.log('bytes', body.length);
})().catch((e) => { console.error(e); process.exit(2); });
