#!/usr/bin/env python3
"""Regenerate docs/VISUAL_SOURCE_REGISTRY.md from source/public/visual-registry-v14.js.

Evidence per curated file/category:
  search-verified  -> listed in docs/RESEARCH_RECEIPTS.md section 4 (page confirmed via web search)
  inherited        -> already referenced by the v53 baseline (commit 6e3ebec) layers
  unverified       -> neither; flagged so it can be checked on-device with INTELLECTUALITY_V14.audit()
"""
import json, re, subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
BASELINE = "6e3ebec"
js = "global.window={};require('./source/public/visual-registry-v14.js');const R=window.INTELLECTUALITY_V14_REGISTRY;" \
     "console.log(JSON.stringify({version:R.version,concepts:R.concepts.map(c=>({k:c.k,label:c.label,subj:c.subj||null,not:c.not||null,files:c.files||[],cats:c.cats||[]})),contrasts:R.contrasts.map(c=>({id:c.id,type:c.type,cmd:c.cmd,a:c.a.label,b:c.b.label})),atlas:R.atlas}))"
R = json.loads(subprocess.run(["node", "-e", js], cwd=ROOT, capture_output=True, text=True, check=True).stdout)
rr = (ROOT / "docs/RESEARCH_RECEIPTS.md").read_text(encoding="utf-8")
sec = rr[rr.index("## 4. Commons files"):]
vfiles = set(re.findall(r"`([^`]+\.(?:png|svg|jpg|gif|JPG|jpeg))`", sec.split("Commons categories")[0]))
vcats = set(x.strip() for x in re.findall(r"`([^`]+)`", sec.split("Commons categories")[1].split("Files inherited")[0]))
base = ""
for f in ["real-visuals-v9.js", "context-visuals-v10.js", "index.html", "visuals-v5.js", "intellectuality-v14.js", "intellectuality-v12.js", "twin-ui-v13.js"]:
    base += subprocess.run(["git", "show", f"{BASELINE}:source/public/{f}"], cwd=ROOT, capture_output=True, text=True).stdout
bl = base.replace(" ", "_").lower()
def inherited(name):
    n = name.replace(" ", "_").lower()
    return n in bl or n.rsplit(".", 1)[0] in bl
MODE = {"dia": "labeled diagram", "spe": "specimen/photo", "mic": "micrograph", "sec": "section", "gra": "graph", "ani": "animation", "unl": "unlabeled recall"}
def src(f):
    if f.startswith("Blausen_"): return "Blausen Medical gallery 2014 (CC BY 3.0)"
    if re.match(r"Gray\d+", f): return "Gray's Anatomy 1918 plate (public domain)"
    if f.startswith("Sobo_1909"): return "Sobotta atlas 1909 plate (public domain)"
    if f.startswith("Brain_human_"): return "Patrick J. Lynch, Yale CAIM (CC BY 2.5)"
    if f.startswith("1421_"): return "OpenStax A&P 2e (CC BY 4.0)"
    return "Wikimedia Commons contributor (license read live)"
def ev(name, is_file):
    if (name in vfiles) if is_file else (name in vcats): return "search-verified"
    if inherited(name): return f"inherited (in v53 baseline {BASELINE})"
    return "unverified in build sandbox (Commons API egress-blocked) — empty ⇒ no visual"
esc = lambda s: str(s).replace("|", "\\|")
rows, cnt = [], {"f": 0, "fv": 0, "fi": 0, "c": 0, "cv": 0, "ci": 0}
for c in R["concepts"]:
    for f in c["files"]:
        e = ev(f[0], True); cnt["f"] += 1; cnt["fv"] += e == "search-verified"; cnt["fi"] += e.startswith("inherited")
        rows.append((c["k"], "file", f[0], MODE.get(f[1], f[1]), f[2] if len(f) > 2 else "—", src(f[0]), e))
    for x in c["cats"]:
        name, trig = (x[0], x[1]) if isinstance(x, list) else (x, "—")
        e = ev(name, False); cnt["c"] += 1; cnt["cv"] += e == "search-verified"; cnt["ci"] += e.startswith("inherited")
        rows.append((c["k"], "category", name, "mixed (modality from file metadata)", trig, "Commons category (per-file license read live)", e))
L = [f"# Visual Source Registry (v{R['version']})\n",
     "Generated by `scripts/gen_visual_registry_doc.py` from `source/public/visual-registry-v14.js` (the file the app runs). Re-run after any registry edit.\n",
     "## How a visual gets on screen\n",
     """1. **Concept from the question, never from the answer.** The stem is matched against the concept patterns; stem hits count double over chapter hits, and longer phrases weigh more. Concepts can carry a `not` guard for stems that share a word but belong elsewhere, e.g. micturition "reflex". A multi-topic lesson title is used only when it names exactly one concept. Otherwise no question visual is shown.
2. **Candidates.** The concept's curated Commons files come first, then up to two Commons categories (`incategory:`). A file or category with a stem trigger is used only when the trigger fires on the stem or chapter, so a scalp-artery item gets `Scalp`, not the facial-nerve drawing. A keyword search runs only when fewer than 3 candidates exist.
3. **Rubric** (`rubric()` in `intellectuality-v14.js`):
   - rejects missing thumbnails, an empty license field, animal/veterinary titles and the reject lists;
   - scores modality fit for the intent, stem and concept overlap, and origin;
   - **demotes by 25 any pre-answer candidate whose title carries key-distinctive words** (leak firewall).
   - Floors: file 14, category 12, keyword 14, look-alike side 12.
4. **Governor** (`window.INTELLECTUALITY_VISUAL_GOVERNOR`, shared by v9, v10 and v14) penalizes: previous screen −100, last 5 screens −40, same session −25, same day −12, cross-concept overuse −30, modality streak −10. It keeps one per-screen dedupe and one network queue (≤2 in flight, 7 s abort, 14-day LRU cache of 160 entries).
5. **Display.**
   - Commons thumbnail embed (lazy, fixed 4:3 box) linked to the file page, with license and artist from `extmetadata`.
   - Before the answer, the caption is neutral.
   - Nothing is downloaded, re-hosted, screenshotted or generated.
""",
     "## Licensing law\n",
     """| Source class | Terms | v14 use |
|---|---|---|
| Wikimedia Commons files (Blausen, Gray's, Sobotta, Lynch/CAIM, OpenStax copies, contributors) | Commons hosts only free licenses (CC0 / PD / CC BY / CC BY-SA / GFDL) | Runtime embed with license and author on every card; empty license ⇒ rejected |
| University atlases (below) | NC-SA or "educational use" | **Link only**, never embedded or copied |
| Source-bank figures (`q.visualData`) | The course's own exam figure | Shown as the exact source figure |
| Generated anatomy | — | **Never** |
""",
     "## Link-only atlases\n", "| Subject | Atlas | Terms |", "|---|---|---|"]
for sub, arr in R["atlas"].items():
    for a in arr: L.append(f"| {sub} | [{a['label']}]({a['href']}) | {a['terms']} |")
L += ["", "## Registry inventory\n",
      f"{len(R['concepts'])} concepts · {cnt['f']} curated files ({cnt['fv']} search-verified, {cnt['fi']} inherited from v53) · {cnt['c']} categories ({cnt['cv']} search-verified, {cnt['ci']} inherited) · {len(R['contrasts'])} discriminator contrasts.\n",
      "\"Search-verified\" means the Commons page was confirmed to exist, with matching title and description, via web search from the build session; direct Commons API calls are egress-blocked there. \"Inherited\" means the v53 production layers already referenced it. Unverified entries fail safe: an empty or missing category returns no rows, and the card then says no trustworthy visual exists. Run `await INTELLECTUALITY_V14.audit({n:60})` on the iPad to see live results.\n",
      "| Concept | Kind | Commons title | Display mode | Stem trigger | Institution / license class | Evidence |", "|---|---|---|---|---|---|---|"]
L += ["| " + " | ".join(esc(x) for x in r) + " |" for r in rows]
L += ["", "## Concept labels and guards\n", "| Concept | Label | Subject limit | `not` guard |", "|---|---|---|---|"]
L += [f"| `{c['k']}` | {esc(c['label'])} | {', '.join(c['subj']) if c['subj'] else 'any'} | {esc(c['not']) if c['not'] else '—'} |" for c in R["concepts"]]
L += ["", "## Discriminator contrasts (autopsy library)\n",
      "A contrast fires only when three things hold: the key matches one pole, the chosen option matches the other, and the frame regex fires on the stem, key or chosen text. Side visuals come from the pole concepts. When no candidate names the chosen side, the card says so instead of substituting.\n",
      "| id | type | command | pole A | pole B |", "|---|---|---|---|---|"]
L += [f"| `{c['id']}` | {c['type']} | {c['cmd']} | {esc(c['a'])} | {esc(c['b'])} |" for c in R["contrasts"]]
(ROOT / "docs/VISUAL_SOURCE_REGISTRY.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print(cnt, len(rows))
